<div class="content">
    <?php View::content(); ?>
    <h3>Editar provincia<h3>

            <?php echo Form::open(); // por defecto llama a la misma url ?>
            <label>Nombre localidad
                <?php echo Form::text('provincia.nombreprovincia') ?></label>
            <?php echo Form::hidden('provincia.id') ?>
            <?php echo Form::submit('Actualizar') ?>
            <?php echo Form::close() ?>
            </div>