<div class="page-header">
    <h1>Provincias</h1>
</div>
<div id="mensajes_flash" >        
    <?php View::content() ?>
</div> 
<?php View::partial('backend/barra_superior_listas', FALSE, array('texto' => 'Crear provincia', 'opciones' => FALSE)); ?>
<?php echo Form::open('admin/provincia', 'post', 'id="formUsuario"') ?>
<div>
    <div class="conjunto">
        <?php echo Form::label('Nombre provincia', 'nombreprovincia', '') ?>
        <div >
            <?php echo Form::text('nombreprovincia') ?>
        </div>
    </div>

</div>
<?php echo Form::close() ?>
<div class="row">
    <div class="col-sm-12">
        <table class="table table-bordered table-responsive">
            <thead>
                <tr>

                    <th>Nombre</th>
                    <th>Editar</th>
                    <th>Borrar</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($listProvincia->items as $prov) { ?>
                    <tr>
                        <td><?php echo $prov->nombreprovincia ?></td>
                        <td><a href="<?php echo PUBLIC_PATH . "admin/provincia/edit/" . $prov->id ?>"><img alt="" src="<?php echo PUBLIC_PATH ?>img/figuras/editar.png"></a></td>
                        <td><a href="<?php echo PUBLIC_PATH . "admin/provincia/del/" . $prov->id ?>"><img alt="" src="<?php echo PUBLIC_PATH ?>img/figuras/eliminar.png"></a></td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
    <?php if ($listProvincia->prev) echo Html::linkAction("index/$listProvincia->prev/", '<< Anterior |'); ?>
    <?php if ($listProvincia->next) echo Html::linkAction("index/$listProvincia->next/", 'Próximo >>'); ?>
</div>
