<div class="content">
    <?php View::content(); ?>
    <h3>Editar oficina<h3>

            <?php echo Form::open(); // por defecto llama a la misma url ?>
            <label>Nombre localidad
                <?php echo Form::text('oficinainscripcion.nombreoficina') ?></label>
            <?php echo Form::hidden('oficinainscripcion.id') ?>
            <?php echo Form::submit('Actualizar') ?>
            <?php echo Form::close() ?>
            </div>