<div class="page-header">
    <h1>Oficinas</h1>
</div>
<div id="mensajes_flash" >        
    <?php View::content() ?>
</div> 
<?php View::partial('backend/barra_superior_listas', FALSE, array('texto' => 'Crear oficina', 'opciones' => FALSE)); ?>
<?php echo Form::open('admin/oficinainscripcion', 'post', 'id="formUsuario"') ?>
<div>
    <div class="conjunto">
        <?php echo Form::label('Nombre oficina', 'nombreoficina', '') ?>
        <div >
            <?php echo Form::text('criterio.nombre') ?>
        </div>
        <?php echo Form::label('Numero oficina', 'numerooficina', '') ?>
        <div >
            <?php echo Form::text('criterio.numero') ?>
        </div>
        <?php echo Form::submit('buscar') ?>
    </div>

</div>
<?php echo Form::close() ?>
<div class="row">
    <div class="col-sm-12">
        <table class="table table-bordered table-responsive">
            <thead>
                <tr>

                    <th>Nombre</th>
                    <th>Número</th>
                    <th>Editar</th>
                    <th>Borrar</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($listOficinainscripcion->items as $ofi) { ?>
                    <tr>
                        <td><?php echo $ofi->nombreoficina ?></td>
                        <td><?php echo $ofi->numerooficina ?></td>
                        <td><a href="<?php echo PUBLIC_PATH . "admin/oficinainscripcion/edit/" . $ofi->id ?>"><img alt="" src="<?php echo PUBLIC_PATH ?>img/figuras/editar.png"></a></td>
                        <td><a href="<?php echo PUBLIC_PATH . "admin/oficinainscripcion/del/" . $ofi->id ?>"><img alt="" src="<?php echo PUBLIC_PATH ?>img/figuras/eliminar.png"></a></td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
    <?php if ($listOficinainscripcion->prev) echo Html::linkAction("index/$listOficinainscripcion->prev/", '<< Anterior |'); ?>
    <?php if ($listOficinainscripcion->next) echo Html::linkAction("index/$listOficinainscripcion->next/", 'Próximo >>'); ?>
</div>
