<div class="content">
    <?php View::content(); ?>
    <h3>Editar Codigos provinciales<h3>

            <?php echo Form::open(); // por defecto llama a la misma url ?>
            <label>Importe $$$
                <?php echo Form::text('codigoprovincial.importecodigo') ?></label>
            <label>N° codigo
                <?php echo Form::text('codigoprovincial.numerocodigoprovincial') ?></label>
            <label>Disponible desde
                <?php echo Form::text('codigoprovincial.fechadesde', array("class" => "datemask")) ?></label>
            <label>Disponible hasta
                <?php echo Form::text('codigoprovincial.fechahasta', array("class" => "datemask")) ?></label>
            <?php echo Form::hidden('codigoprovincial.id') ?>
            <?php echo Form::submit('Actualizar') ?>
            <?php echo Form::close() ?>
            </div>