<div class="page-header">
    <h1>Códigos provinciales</h1>
</div>
<div id="mensajes_flash" >        
    <?php View::content() ?>
</div> 
<?php View::partial('backend/barra_superior_listas', FALSE, array('texto' => 'Crear código', 'opciones' => FALSE)); ?>
<?php echo Form::open('admin/codigoprovincial', 'post', 'id="formUsuario"') ?>
<div>
    <div class="conjunto">
        <?php echo Form::label('N° código', 'numerocodigoprovincial', '') ?>
        <div >
            <?php echo Form::text('numerocodigoprovincial') ?>


        </div>
    </div>

</div>
<?php echo Form::close() ?>
<div class="row">
    <div class="col-sm-12">
        <table class="table table-bordered table-responsive">
            <thead>
                <tr>

                    <th>Importe $</th>
                    <th>Nº código</th>
                    <th>Disponible desde</th>
                    <th>Disponible hasta</th>
                    <th>Editar</th>
                    <th>Borrar</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($listCodigoprovincial->items as $l) { ?>
                    <tr>
                        <td><?php echo $l->importecodigo ?></td>
                        <td><?php echo $l->numerocodigoprovincial ?></td>
                        <td><?php echo $l->fechadesde ?></td>
                        <td><?php echo $l->fechahasta ?></td>
                        <td><a href="<?php echo PUBLIC_PATH . "admin/codigoprovincial/edit/" . $l->id ?>"><img alt="" src="<?php echo PUBLIC_PATH ?>/img/figuras/editar.png"></a></td>
                        <td><a href="<?php echo PUBLIC_PATH . "admin/codigoprovincial/del/" . $l->id ?>"><img alt="" src="<?php echo PUBLIC_PATH ?>/img/figuras/eliminar.png"></a></td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
    <?php if ($listCodigoprovincial->prev) echo Html::linkAction("index/$listCodigoprovincial->prev/", '<< Anterior |'); ?>
    <?php if ($listCodigoprovincial->next) echo Html::linkAction("index/$listCodigoprovincial->next/", 'Próximo >>'); ?>
</div>
