<div class="content">
    <?php View::content(); ?>
    <h3>Linkrecuperacion</h3>
    <ul>
    <?php foreach ($listLinkrecuperacion->items as $item) : ?>
    <li>
        <?php echo Html::linkAction("edit/$item->id/", 'Editar') ?>
        <?php echo Html::linkAction("del/$item->id/", 'Borrar') ?>
        <strong><?php echo $item->enlaceactivo ?> -<?php echo $item->enlacerecuperacion ?> -<?php echo $item->fechadeemision ?></strong>
    </li>
    <?php endforeach; ?>
    </ul>
 
     <!-- ejemplo manual de paginador, hay partial listos en formato digg, clasic,.... -->
    <?php if($listLinkrecuperacion->prev) echo Html::linkAction("index/$listLinkrecuperacion->prev/", '<< Anterior |'); ?>
    <?php if($listLinkrecuperacion->next) echo Html::linkAction("index/$listLinkrecuperacion->next/", 'Próximo >>'); ?>
</div>