<div class="content">
<?php View::content(); ?>
<h3>Crear Operacion<h3>
 
<?php echo Form::open(); // por defecto llama a la misma url ?>
 
         <label>Nombre 
        <?php echo Form::text('operacion.nombreoperacion') ?></label>
        <label>Descripción 
        <?php echo Form::text('operacion.descripcionoperacion') ?></label>
       <label>Fecha baja 
        <?php echo Form::text('operacion.fechabajaoperacion') ?></label>
        <label>idRol
        <?php echo Form::text('operacion.idrol') ?></label>
 
        <?php echo Form::submit('Agregar') ?>
 
<?php echo Form::close() ?>
</div>