<div class="content">
    <?php View::content(); ?>
    <h3>Editar Operacion<h3>

            <?php echo Form::open(); // por defecto llama a la misma url ?>

            <label>Descripcion operacion
                <?php echo Form::text('operacion.descripcionoperacion') ?></label>
            <label>Nombre operacion
                <?php echo Form::text('operacion.nombreoperacion') ?></label>
            <label>Fecha baja operacion
                <?php echo Form::text('operacion.fechabajaoperacion') ?></label>
            <?php echo Form::hidden('operacion.id') ?>
            <?php echo Form::hidden('operacion.idrol') ?>
            <?php echo Form::submit('Actualizar') ?>

            <?php echo Form::close() ?>
            </div>