<div class="content">
    <?php View::content(); ?>
    <h3>Operacion</h3>
    <ul>
    <?php foreach ($listOperacion->items as $item) : ?>
    <li>
        <?php echo Html::linkAction("edit/$item->id/", 'Editar') ?>
        <?php echo Html::linkAction("del/$item->id/", 'Borrar') ?>
        <strong><?php echo $item->descripcionoperacion ?> - <?php echo $item->nombreoperacion ?> - <?php echo $item->fechabajaoperacion ?></strong>
    </li>
    <?php endforeach; ?>
    </ul>
 
     <!-- ejemplo manual de paginador, hay partial listos en formato digg, clasic,.... -->
    <?php if($listOperacion->prev) echo Html::linkAction("index/$listOperacion->prev/", '<< Anterior |'); ?>
    <?php if($listOperacion->next) echo Html::linkAction("index/$listOperacion->next/", 'Próximo >>'); ?>
</div>