<div class="content">
    <?php View::content(); ?>
    <h3>Editar tipos de reclamos<h3>
            <div class="row">
                <?php echo Form::open(); // por defecto llama a la misma url ?>

                <label>Nombre
                    <?php echo Form::text('tiporeclamo.nombretiporeclamo') ?></label>
                <label>Descripcion
                    <?php echo Form::text('tiporeclamo.descripciontiporeclamo') ?></label>
                <label>Fecha desde
                    <?php echo Form::text('tiporeclamo.fechadesde', array("class" => "datemask")) ?></label>
                <label>Fecha hasta
                    <?php echo Form::text('tiporeclamo.fechahasta', array("class" => "datemask")) ?></label>
                <?php echo Form::hidden('tiporeclamo.id') ?>
                <?php echo Form::submit('Actualizar') ?>
                <?php echo Form::close() ?>
            </div>
            </div>