<div class="content">
    <?php View::content(); ?>
    <h3>Localidad</h3>
    <ul>
    <?php foreach ($listLocalidad->items as $item) : ?>
    <li>
        <?php echo Html::linkAction("edit/$item->id/", 'Editar') ?>
        <?php echo Html::linkAction("del/$item->id/", 'Borrar') ?>
        <strong><?php echo $item->nombrelocalidad ?></strong>
    </li>
    <?php endforeach; ?>
    </ul>
     <!-- ejemplo manual de paginador, hay partial listos en formato digg, clasic,.... -->
    <?php if($listLocalidad->prev) echo Html::linkAction("index/$listLocalidad->prev/", '<< Anterior |'); ?>
    <?php if($listLocalidad->next) echo Html::linkAction("index/$listLocalidad->next/", 'Próximo >>'); ?>
</div>