<div class="content">
    <?php View::content(); ?>
    <h3>Crear reclamoerroractaestado<h3>

            <?php echo Form::open(); // por defecto llama a la misma url ?>
            <label>Nombre reclamoerroractaestado
                <?php echo Form::text('reclamoerroractaestado.nombrereclamoerroractaestado') ?></label>
            <?php echo Form::submit('Agregar') ?>
            <?php echo Form::close() ?>
            </div>