<div class="content">
    <?php View::content(); ?>
    <h3>Editar reclamoerroractaestado<h3>

            <?php echo Form::open(); // por defecto llama a la misma url ?>
            <label>Nombre
                <?php echo Form::text('reclamoerroractaestado.nombrereclamoerroractaestado') ?></label>
            <?php echo Form::hidden('reclamoerroractaestado.id') ?>
            <?php echo Form::submit('Actualizar') ?>
            <?php echo Form::close() ?>
            </div>