<div class="content">
    <?php View::content(); ?>
    <h3>Reclamo Error Acta Estado</h3>
    <ul>
    <?php foreach ($listReclamoErrorActaEstado->items as $item) : ?>
    <li>
        <?php echo Html::linkAction("edit/$item->id/", 'Editar') ?>
        <?php echo Html::linkAction("del/$item->id/", 'Borrar') ?>
        <strong><?php echo $item->nombrereclamoerroractaestado ?></strong>
    </li>
    <?php endforeach; ?>
    </ul>
 
     <!-- ejemplo manual de paginador, hay partial listos en formato digg, clasic,.... -->
    <?php if($listReclamoErrorActaEstado->prev) echo Html::linkAction("index/$listReclamoErrorActaEstado->prev/", '<< Anterior |'); ?>
    <?php if($listReclamoErrorActaEstado->next) echo Html::linkAction("index/$listReclamoErrorActaEstado->next/", 'Próximo >>'); ?>
</div>