<!DOCTYPE html>
<html>
    <head>
        <!--Import Google Icon Font-->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <!--Import materialize.css-->
        <link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen,projection"/>
        <link rel="stylesheet" type="text/css" href="css/registro.css">

        <!--Let browser know website is optimized for mobile-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>
    <title>Recuperar cuenta</title>
    <body>

        <!-- Header con titulo -->
        <nav>
            <div class="nav-wrapper">
                <a href="#" class="brand-logo center">Recupera tu cuenta</a>
            </div>
        </nav>  

        <!-- Formato del formulario con boton al final -->
        <div class="row">
        </div>
        <div class="center row">
            <label>Ingresa tu nueva clave</label>
        </div>
        <div class="row">
        </div>
        <div class="center row">
            <form class="col s12"> 

                <div class="row">
                    <div class="input-field">
                        <input id="clave" placeholder="Clave" type="text" class="validate">
                        <label for="clave" data-success="correcto">Clave</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field">
                        <input id="clave2" placeholder="Clave" type="text" class="validate">
                        <label for="clave" data-success="correcto">Repetir clave</label>
                    </div>
                </div>
                <div class="form-actions">
                    <?php if (clave == clave2) { ?>
                        <?php echo Form::submit('Recuperar', 'class="btn btn-primary"') ?>
                    <?php } else { ?>
                        <?php Flash::error("Las claves no coinciden") ?>
                    <?php } ?>

                </div>
            </form>
        </div>
        <div class="row">
        </div>
        <div class="row">
        </div>
        <div class="right row"> 
            <?php echo html::link('ayuda', "Necesitas ayuda? Contacta al soporte tecnico de gestion digital de actas!", array("class" => "one", "id" => "download-button")) ?>
        </div>
    </div>

    <!--Import jQuery before materialize.js-->
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script type="text/javascript" src="js/materialize.min.js"></script>
    <script type="text/javascript" src="js/jquery/jquery.kumbiaphp.js"></script>
    <!-- En init.js esta declarada la inicializacion del selector que se utiliza en tipo nro telefono-->
    <script src="js/init.js"></script>
    <!-- En registroUsuario.js declarada toda la logica pertinente al registro del usuario. Tambien esta la funcion que evita que se agregue la letra
    "e" en los input fields de tipo number-->
    <script src="js/olvido.js"></script>
</body>
</html>
