<!DOCTYPE html>
<html>
    <head>
        <!--Import Google Icon Font-->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <!-- Custom Theme Style -->
        <link href="<?php echo PUBLIC_PATH ?>gentelella/css/custom.min.css" rel="stylesheet">
        <!--Import materialize.css-->
        <link type="text/css" rel="stylesheet" href="<?php echo PUBLIC_PATH ?>css/materialize.min.css"  media="screen,projection"/>
        <link rel="stylesheet" type="text/css" href="<?php echo PUBLIC_PATH ?>css/baseFonts.css">
        <link rel="stylesheet" type="text/css" href="<?php echo PUBLIC_PATH ?>css/alerta.css">
        
        <!--Let browser know website is optimized for mobile-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>
    <title>Recuperar cuenta</title>
    <body>

        <!-- Header con titulo -->
        <nav>
            <div class="nav-wrapper">
                <a href="#" class="brand-logo center">Recupera tu cuenta</a>
            </div>
        </nav>  

        <!-- Formato del formulario con boton al final -->
    <div class="center row">
        <div id="mensajes_flash" >        
            <?php View::content() ?>
        </div> 
        
        <label>Ingresa tu nueva clave</label>
            <?php echo Form::open("", 'post', array('class' => "col s12")); // por defecto llama a la misma url ?>
            <div class="row">
                <div class="input-field">
                    <?php echo Form::text('usuarios.login', array('placeholder' => "login", 'class' => "validate", "disabled" => "disabled")) ?>
                    <label for="id" data-success="correcto">Login</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field">
                    <?php echo Form::pass('usuarios.clave', array('id' => "clave", 'placeholder' => "Clave", 'text' => "clave", 'class' => "validate")) ?>
                    <label for="clave" data-success="correcto">Clave nueva</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field">
                    <?php echo Form::pass('usuarios.repetida', array('id' => "clave", 'placeholder' => "Clave", 'text' => "clave", 'class' => "validate")) ?>
                    <label for="repetida" data-success="correcto">Repetir clave</label>
                </div>
            </div>
            <div class="form-actions">
                <?php echo Form::submit('Recuperar', 'class="btn btn-primary"') ?>
            </div>
            <?php echo Form::close() ?>
    </div>

    <!--Import jQuery before materialize.js-->
    //<script type="text/javascript" src="<?php echo PUBLIC_PATH ?>js/jquery-3.2.1.min.js"></script>
    <script type="text/javascript" src="<?php echo PUBLIC_PATH ?>js/materialize.min.js"></script>
    <script type="text/javascript" src="<?php echo PUBLIC_PATH ?>js/jquery/jquery.kumbiaphp.js"></script>
    <!-- En init.js esta declarada la inicializacion del selector que se utiliza en tipo nro telefono-->
    <script src="<?php echo PUBLIC_PATH ?>js/init.js"></script>
    <!-- En registroUsuario.js declarada toda la logica pertinente al registro del usuario. Tambien esta la funcion que evita que se agregue la letra
    "e" en los input fields de tipo number-->
</body>
</html>
