<div class="content">
    <?php View::content(); ?>
    <h3>Crear estados de reclamos error acta<h3>

            <?php echo Form::open(); // por defecto llama a la misma url ?>
            <label>Nombre
                <?php echo Form::text('estadoreclamoerroracta.nombreestadoreclamoerroracta') ?></label>
            <label>Descripción
                <?php echo Form::text('estadoreclamoerroracta.descripcion') ?></label>
            <label>Fecha desde
                <?php echo Form::text('estadoreclamoerroracta.fechadesde', array("class" => "datemask")) ?></label>
            <label>Fecha hasta
                <?php echo Form::text('estadoreclamoerroracta.fechahasta', array("class" => "datemask")) ?></label>
            <?php echo Form::submit('Agregar') ?>

            <?php echo Form::close() ?>
            </div>