<!DOCTYPE html>
<html>
    <head>
        <!-- Custom Theme Style -->
        <link href="<?php echo PUBLIC_PATH ?>gentelella/css/custom.min.css" rel="stylesheet">
        <!-- jQuery -->
        <script src="<?php echo PUBLIC_PATH ?>gentelella/css/jquery.min.js"></script>
        <!--Import Google Icon Font-->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link type="text/css" rel="stylesheet" href="<?php echo PUBLIC_PATH ?>css/materialize.min.css"  media="screen,projection"/>
        <link type="text/css" rel="stylesheet" href="<?php echo PUBLIC_PATH ?>css/listado.css"  media="screen,projection"/>
        <link rel="stylesheet" type="text/css" href="<?php echo PUBLIC_PATH ?>css/baseFonts.css">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>
    <title>Recuperar contrase&ntilde;a?</title>
    <body>

        <!-- Header con titulo -->
         <nav class="nav-extended">
            <div class="nav-wrapper">
                <div class="nav-container">
                    <a href="#" class="brand-logo__link"><?php echo Html::img('logo.png', 'Menu', array("width" => "48px", "height" => "48px")) ?></a>
                    <?php echo Html::link("", "<div class=\"header-logo\">GESTIÓN DE ACTAS DIGITALES</div>"); ?>
                    <div class="nav-submenu">
                        > Recuperar contrase&ntilde;a?
                    </div>
                </div>
            </div>
        </nav>

        <div class="center row withTopPad">
        <label><span style="font-size: 18px; margin-top: 15px;" class="white-text">Ingresa tu email</span></label>

            <?php echo view::content() ?>
            <?php echo Form::open("", 'post', array('class' => "col s12")); // por defecto llama a la misma url ?>
            <div class="input-field">
                <!--<input id="email" placeholder="Email" type="email" class="validate">-->
                <?php echo Form::text('usuarios.email', array('id' => "email", 'placeholder' => "Email", 'type' => "email", 'class' => "validate")) ?>
                <label for="email" data-error="Mail inválido" data-success="correcto">Email</label>
            </div>
            <div class="form-actions">
                <?php echo Form::submit('Enviar', 'class="btn btn-primary blue darken-3"') ?>
            </div>
            <?php echo Form::close() ?>
        </div>

        <!--Import jQuery before materialize.js-->
        <script type="text/javascript" src="<?php echo PUBLIC_PATH ?>js/jquery-3.2.1.min.js"></script>
        <script type="text/javascript" src="<?php echo PUBLIC_PATH ?>js/materialize.min.js"></script>
        <script type="text/javascript" src="<?php echo PUBLIC_PATH ?>js/jquery/jquery.kumbiaphp.js"></script>
        <!-- En init.js esta declarada la inicializacion del selector que se utiliza en tipo nro telefono-->
        <script src="<?php echo PUBLIC_PATH ?>js/init.js"></script>
        <!-- En registroUsuario.js declarada toda la logica pertinente al registro del usuario. Tambien esta la funcion que evita que se agregue la letra
        "e" en los input fields de tipo number-->
    </body>
</html>
