<!DOCTYPE html>
<html>
    <head>
        <!--Import Google Icon Font-->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <!--Import materialize.css-->
        <link href="<?php echo PUBLIC_PATH ?>gentelella/css/custom.min.css" rel="stylesheet">
        <link type="text/css" rel="stylesheet" href="<?php echo PUBLIC_PATH ?>css/materialize.min.css"  media="screen,projection"/>
        <link rel="stylesheet" type="text/css" href="<?php echo PUBLIC_PATH ?>css/baseFonts.css">
        <link rel="stylesheet" type="text/css" href="<?php echo PUBLIC_PATH ?>css/alerta.css">
        

        <!--Let browser know website is optimized for mobile-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>
    <title>Recuperar contrase&ntilde;a?</title>
    <body>

        <!-- Header con título -->
        <nav>
            <div class="nav-wrapper">
                <a href="#" class="brand-logo center">Recuperar contrase&ntilde;a</a>
            </div>
        </nav>  

        <div class="center row withTopPad">
            <label>Ingresa tu email</label>
            <?php echo view::content() ?>
            <?php echo Form::open("", 'post', array('class' => "col s12")); // por defecto llama a la misma url ?>
            <div class="input-field">
                <!--<input id="email" placeholder="Email" type="email" class="validate">-->
                <?php echo Form::text('usuarios.email', array('id' => "email", 'placeholder' => "Email", 'type' => "email", 'class' => "validate")) ?>
                <label for="email" data-error="Mail inválido" data-success="correcto">Email</label>
            </div>
            <div class="form-actions">
                <?php echo Form::submit('Enviar', 'class="btn btn-primary"') ?>
            </div>
            <?php echo Form::close() ?>
        </div>

    <!--Import jQuery before materialize.js-->
    <script type="text/javascript" src="<?php echo PUBLIC_PATH ?>js/jquery-3.2.1.min.js"></script>
    <script type="text/javascript" src="<?php echo PUBLIC_PATH ?>js/materialize.min.js"></script>
    <script type="text/javascript" src="<?php echo PUBLIC_PATH ?>js/jquery/jquery.kumbiaphp.js"></script>
    <!-- En init.js esta declarada la inicializacion del selector que se utiliza en tipo nro telefono-->
    <script src="<?php echo PUBLIC_PATH ?>js/init.js"></script>
    <!-- En registroUsuario.js declarada toda la logica pertinente al registro del usuario. Tambien esta la funcion que evita que se agregue la letra
    "e" en los input fields de tipo number-->
</body>
</html>
