<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <!-- Meta, title, CSS, favicons, etc. -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Gestion Digital de Actas</title>

        <!-- Bootstrap -->
        <link href="<?php echo PUBLIC_PATH ?>gentelella/css/bootstrap.min.css" rel="stylesheet">
        <!-- Font Awesome -->
        <link href="<?php echo PUBLIC_PATH ?>gentelella/css/font-awesome.min.css" rel="stylesheet">
        <!-- NProgress -->
        <link href="<?php echo PUBLIC_PATH ?>gentelella/css/nprogress.css" rel="stylesheet">
        <!-- Custom Theme Style -->
        <link href="<?php echo PUBLIC_PATH ?>gentelella/css/custom.min.css" rel="stylesheet">
        <!-- jQuery -->
        <script src="<?php echo PUBLIC_PATH ?>gentelella/css/jquery.min.js"></script>
        <!-- Bootstrap -->
        <script src="<?php echo PUBLIC_PATH ?>gentelella/css/bootstrap.min.js"></script>
        <!-- Datatables -->
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/jquery.dataTables.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/dataTables.bootstrap.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/dataTables.buttons.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/buttons.bootstrap.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/buttons.flash.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/buttons.html5.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/buttons.print.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/jquery.maskedinput.js"></script>
    </head>

    <body class="nav-md">
        <div class="container body">
            <div class="main_container">
                <div class="col-md-3 left_col">
                    <div class="left_col scroll-view">
                        <div class="navbar nav_title" style="border: 0;">
                            <a href="<?php echo PUBLIC_PATH ?>" class="site_title"><i class="fa fa-home"></i> <span>Administración general</span></a>-->
                        </div>

                        <br />

                        <!-- sidebar menu -->
                        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                            <div class="menu_section">
                                <ul class="nav side-menu">
                                    <?php if (Auth::get("login") == "sadmin") { ?>
                                        <li><a href="<?php echo PUBLIC_PATH ?>admin/roles"><i class="fa fa-users"></i> Roles</a>
                                        <li><a href="<?php echo PUBLIC_PATH ?>admin/recursos"><i class="fa fa-share-alt"></i> Recursos</a>
                                        <li><a href="<?php echo PUBLIC_PATH ?>admin/privilegios"><i class="fa fa-star"></i> Privilegios</a>
                                        <li><a href="<?php echo PUBLIC_PATH ?>admin/usuarios"><i class="fa fa-user-circle"></i> Usuarios</a>
                                        <li><a href="<?php echo PUBLIC_PATH ?>admin/provincia"><i class="fa fa-map-marker"></i> Provincias</a>
                                        <li><a href="<?php echo PUBLIC_PATH ?>admin/departamento"><i class="fa fa-map-marker"></i> Departamentos</a>
                                        <li><a href="<?php echo PUBLIC_PATH ?>admin/localidad"><i class="fa fa-map-marker"></i> Localidades</a>
                                        <li><a href="<?php echo PUBLIC_PATH ?>admin/codigoprovincial"><i class="fa fa-ticket"></i> Códigos</a>
                                        <li><a href="<?php echo PUBLIC_PATH ?>admin/tiporeporte"><i class="fa fa-newspaper-o"></i> Tipo Reporte</a>
                                        <li><a href="<?php echo PUBLIC_PATH ?>admin/tiporeclamo"><i class="fa fa-newspaper-o"></i> Tipo Reclamo</a>
                                        <li><a href="<?php echo PUBLIC_PATH ?>admin/tipolibro"><i class="fa fa-newspaper-o"></i> Tipo Libro</a>
                                        <li><a href="<?php echo PUBLIC_PATH ?>admin/oficinainscripcion"><i class="fa fa-home"></i> Oficinas</a>
                                        <li><a href="<?php echo PUBLIC_PATH ?>admin/estadosolicitud"><i class="fa fa-circle-o-notch"></i> Estados solicitud</a>
                                        <li><a href="<?php echo PUBLIC_PATH ?>admin/estadoreclamoerroracta"><i class="fa fa-circle-o-notch"></i> Estados reclamo error acta</a>
                                        <li><a href="<?php echo PUBLIC_PATH ?>admin/estadoimagenacta"><i class="fa fa-circle-o-notch"></i> Estados imagen acta</a>
                                        <li><a href="<?php echo PUBLIC_PATH ?>admin/parentesco"><i class="fa fa-user-plus"></i> Parentesco</a>
                                        <li><a href="<?php echo PUBLIC_PATH ?>admin/reporte"><i class="fa fa-tasks"></i> Reportes</a>
                                        <?php } ?>
                                        <?php if (Auth::get("login") == "admin") { ?>
                                        <li><a href="<?php echo PUBLIC_PATH ?>admin/provincia"><i class="fa fa-map-marker"></i> Provincias</a>
                                        <li><a href="<?php echo PUBLIC_PATH ?>admin/departamento"><i class="fa fa-map-marker"></i> Departamentos</a>
                                        <li><a href="<?php echo PUBLIC_PATH ?>admin/localidad"><i class="fa fa-map-marker"></i> Localidades</a>
                                        <li><a href="<?php echo PUBLIC_PATH ?>admin/codigoprovincial"><i class="fa fa-ticket"></i> Códigos</a>
                                        <li><a href="<?php echo PUBLIC_PATH ?>admin/tiporeporte"><i class="fa fa-newspaper-o"></i> Tipo Reporte</a>
                                        <li><a href="<?php echo PUBLIC_PATH ?>admin/tiporeclamo"><i class="fa fa-newspaper-o"></i> Tipo Reclamo</a>
                                        <li><a href="<?php echo PUBLIC_PATH ?>admin/tipolibro"><i class="fa fa-newspaper-o"></i> Tipo Libro</a>
                                        <li><a href="<?php echo PUBLIC_PATH ?>admin/oficinainscripcion"><i class="fa fa-home"></i> Oficinas</a>
                                        <li><a href="<?php echo PUBLIC_PATH ?>admin/estadosolicitud"><i class="fa fa-circle-o-notch"></i> Estados solicitud</a>
                                        <li><a href="<?php echo PUBLIC_PATH ?>admin/estadoreclamoerroracta"><i class="fa fa-circle-o-notch"></i> Estados reclamo error acta</a>
                                        <li><a href="<?php echo PUBLIC_PATH ?>admin/estadoimagenacta"><i class="fa fa-circle-o-notch"></i> Estados imagen acta</a>
                                        <li><a href="<?php echo PUBLIC_PATH ?>admin/parentesco"><i class="fa fa-user-plus"></i> Parentesco</a>
                                        <li><a href="<?php echo PUBLIC_PATH ?>admin/reporte"><i class="fa fa-tasks"></i> Reportes</a>
                                        <?php } ?>
                                </ul>
                            </div>
                        </div>
                        <!-- /sidebar menu -->
                        <!-- /menu footer buttons -->
                    </div>
                </div>

                <!-- top navigation -->

                <!-- page content -->
                <div class="right_col" role="main">
                    <?php echo View::content() ?>
                </div>
                <!-- /page content -->

            </div>
        </div>
        <div id='cabecera' class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <div class="nav-collapse">
                        <?php View::renderMenu(Menu::BACKEND) ?>
                        <ul class="nav pull-right">
                            <li class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#" style="text-transform: capitalize;">
                                    <?php eh(Auth::get('nombres')) ?>
                                    <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">
                                    <li><?php echo Html::link('admin/index/logout', 'Salir') ?></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <!-- FastClick -->
        <script src="<?php echo PUBLIC_PATH ?>gentelella/css/fastclick.js"></script>
        <!-- NProgress -->
        <script src="<?php echo PUBLIC_PATH ?>gentelella/css/nprogress.js"></script>
        <!-- Custom Theme Scripts -->
        <script src="<?php echo PUBLIC_PATH ?>gentelella/css/custom.min.js"></script>
        <script >$(".datemask").mask("99/99/9999")</script>
    </body>
</html>
