<!DOCTYPE html>
<html>
    <head>
        <!--Import Google Icon Font-->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link type="text/css" rel="stylesheet" href="<?php echo PUBLIC_PATH ?>css/materialize.min.css"  media="screen,projection"/>
        <link type="text/css" rel="stylesheet" href="<?php echo PUBLIC_PATH ?>css/listado.css"  media="screen,projection"/>

        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>
    <div id="mensajes_flash" >        
        <?php View::content() ?>
    </div> 
    <title>Listado Solicitudes</title>

        <!-- Header con titulo -->
        <nav>
            <div class="nav-wrapper">
                <a href="#" class="brand-logo center">Listado solicitudes</a>
            </div>
        </nav>  
        <ul class="left-align dropdown-menu">
            <li><?php echo Html::img('home.png', 'Menu', array("width" => "48px", "height" => "48px")) ?></li>
            <li><?php echo Html::link("ciudadano/", "Menu"); ?></li>
        </ul>
        <ul class="right-align dropdown-menu">
            <li><?php echo Html::link('admin/index/logout', 'Salir') ?></li>
        </ul>
        <?php echo Form::close() ?>
        <div class="row">
            <div class="col-sm-12">
                <table class="table table-bordered table-responsive">
                    <thead>
                        <tr>

                            <th>Nombre propietario acta</th>
                            <th>N° de solicitud</th>
                            <th>Parentesco</th>
                            <th>Cupon de pago</th>
                            <th>Tipo solicitud acta</th>
                            <th>Fecha solicitud </th>
                            <th>Estado solicitud </th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($listSolicitudacta as $as) { ?>
                            <tr>
                                <td><?php echo $as->nombrepropietarioacta ?></td>
                                <td><?php echo $as->numerosolicitud ?></td>
                                <td><?php echo $as->nombreparentesco ?></td>
                                <td><?php echo $as->codigodepago ?></td>
                                <td><?php echo $as->nombretiposolicitud ?></td>
                                <td><?php echo $as->fechacambioestado ?></td>
                                <td><?php echo $as->nombreestadosolicitud ?></td>
                            </tr>
                        <?php } ?>
                    </tbody>
                </table>
            </div>
        </div>
</html>