<!DOCTYPE html>
<html>
    <head>
        <!-- Bootstrap -->
        <link href="<?php echo PUBLIC_PATH ?>gentelella/css/bootstrap.min.css" rel="stylesheet">
        <!-- Font Awesome -->
        <link href="<?php echo PUBLIC_PATH ?>gentelella/css/font-awesome.min.css" rel="stylesheet">
        <!-- NProgress -->
        <link href="<?php echo PUBLIC_PATH ?>gentelella/css/nprogress.css" rel="stylesheet">
        <!-- Custom Theme Style -->
        <link href="<?php echo PUBLIC_PATH ?>gentelella/css/custom.min.css" rel="stylesheet">
        <!-- jQuery -->
        <script src="<?php echo PUBLIC_PATH ?>gentelella/css/jquery.min.js"></script>
        <!-- Bootstrap -->
        <script src="<?php echo PUBLIC_PATH ?>gentelella/css/bootstrap.min.js"></script>
        <!-- Custom Theme Style -->

        <!--Import Google Icon Font-->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link type="text/css" rel="stylesheet" href="<?php echo PUBLIC_PATH ?>css/materialize.min.css"  media="screen,projection"/>
        <link type="text/css" rel="stylesheet" href="<?php echo PUBLIC_PATH ?>css/listado.css"  media="screen,projection"/>
        <link rel="stylesheet" type="text/css" href="<?php echo PUBLIC_PATH ?>css/baseFonts.css">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>
    <body>
        <div id="mensajes_flash" >        
            <?php View::content() ?>
        </div> 
        <title>Listado Solicitudes</title>

        <!-- Header con titulo -->
        <nav class="nav-extended">
            <div class="nav-wrapper">
                <div class="nav-container">
                    <a href="#" class="brand-logo__link"><?php echo Html::img('logo.png', 'Menu', array("width" => "48px", "height" => "48px")) ?></a>
                    <?php echo Html::link("ciudadano/", "<div class=\"header-logo\">GESTIÓN DE ACTAS DIGITALES</div>"); ?>
                    <div class="nav-submenu">
                        > Actas digitales > Mis solicitudes
                    </div>
                </div>
                <div class="user-container">
                    <i style="margin-right: 5px" class="large material-icons">account_circle</i>
                    <?php echo Auth::get('nombres') ?>
                    <div style="margin-left: 5px; padding-right: 5px"> | 
                        <?php echo Html::link('admin/index/logout', 'Cerrar sesión') ?>
                    </div>
                </div>
            </div>
        </nav>
        <div class="row">
            <div class="col m4 search-input">
                <i class="material-icons white-text">search</i>
                <input class="" type="text" id="myInput" onkeyup="myFunction()" placeholder="Buscar por nombre propietario...">
            </div>
             <div class="col m4 search-input">
                <i class="material-icons white-text">search</i>
                <input class="" type="text" id="myInput2" onkeyup="myFunction2()" placeholder="Buscar por fecha solicitud...">
            </div>
             <div class="col m4 search-input">                
                <i class="material-icons white-text">search</i>
                <input class="" type="text" id="myInput3" onkeyup="myFunction3()" placeholder="Buscar por cupon de pago...">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <table class="table table-bordered table-responsive striped" id="myTable">
                <thead>
                    <tr>

                        <th>Nombre propietario acta</th>
                        <th>N° de solicitud</th>
                        <th>Parentesco</th>
                        <th>Cupon de pago</th>
                        <th>Tipo libro</th>
                        <th>Fecha solicitud </th>
                        <th>Estado solicitud </th>
                        <th>Eliminar </th>
                        <th>Pagar </th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($listSolicitudacta as $as) { ?>
                        <tr datossolicitud = "<?php echo $as->id ?>">
                            <td class="data-cell"><?php echo $as->nombrepropietarioacta ?></td>
                            <td class="data-cell"><?php echo $as->id ?></td>
                            <td class="data-cell"><?php echo $as->nombreparentesco ?></td>
                            <td class="data-cell"><?php echo $as->codigodepago ?></td>
                            <td class="data-cell"><?php echo $as->nombrelibro ?></td>
                            <td class="data-cell"><?php echo UtilApp::formatea_fecha_bd_to_pantalla($as->fechacambioestado) ?></td>
                            <td class="data-cell"><?php echo $as->nombreestadosolicitud ?></td>
                            <?php if ($as->nombreestadosolicitud == "Pendiente de pago") { ?>
                                <td></td>
                                <td></td>
                            <?php } ?> 
                            <?php if ($as->nombreestadosolicitud == "Confirmada") { ?>
                                <td><a class="cancelar" href="<?php echo PUBLIC_PATH . "ciudadano/listado/cancelar/" . $as->id ?>"><i class="small material-icons black-text">delete</i></a></td>
                                <td><a class="pagar" href="<?php echo PUBLIC_PATH . "ciudadano/listado/pagar/" . $as->id ?>" class = 'botonpagar'><i class="small material-icons">payment</i></a></td>
                            <?php } ?> 
                            <?php if ($as->nombreestadosolicitud == "Pagada") { ?>
                                <td></td>
                                <td><a><i class="small material-icons green-text">check</i></a></td>
                            <?php } ?> 
                            <?php if ($as->nombreestadosolicitud == "Cancelada") { ?>
                                <td></td>
                                <td></td>
                            <?php } ?> 
                            <?php if ($as->nombreestadosolicitud == "Enviada al archivo") { ?>
                                <td></td>
                                <td></td>
                            <?php } ?> 
                        </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
    <script type="text/javascript">
        (function () {

        })();

    </script>
    <script>
        $('#myTable tbody tr').on('click', function () {
        })
        function myFunction() {
            // Declare variables 
            var input, filter, table, tr, td, i;
            input = document.getElementById("myInput");
            filter = input.value.toUpperCase();
            table = document.getElementById("myTable");
            tr = table.getElementsByTagName("tr");

            // Loop through all table rows, and hide those who don't match the search query
            for (i = 0; i < tr.length; i++) {
                td = tr[i].getElementsByTagName("td")[0];
                if (td) {
                    if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
                        tr[i].style.display = "";
                    } else {
                        tr[i].style.display = "none";
                    }
                }
            }
        }
        function myFunction2() {
            // Declare variables 
            var input, filter, table, tr, td, i;
            input = document.getElementById("myInput2");
            filter = input.value.toUpperCase();
            table = document.getElementById("myTable");
            tr = table.getElementsByTagName("tr");

            // Loop through all table rows, and hide those who don't match the search query
            for (i = 0; i < tr.length; i++) {
                td = tr[i].getElementsByTagName("td")[5];
                if (td) {
                    if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
                        tr[i].style.display = "";
                    } else {
                        tr[i].style.display = "none";
                    }
                }
            }
        }
        function myFunction3() {
            // Declare variables 
            var input, filter, table, tr, td, i;
            input = document.getElementById("myInput3");
            filter = input.value.toUpperCase();
            table = document.getElementById("myTable");
            tr = table.getElementsByTagName("tr");

            // Loop through all table rows, and hide those who don't match the search query
            for (i = 0; i < tr.length; i++) {
                td = tr[i].getElementsByTagName("td")[3];
                if (td) {
                    if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
                        tr[i].style.display = "";
                    } else {
                        tr[i].style.display = "none";
                    }
                }
            }
        }
    // Para mostrar mensajes de confirmacion en los casos de cancelar y pagar solicitud
    $('.cancelar').on('click', function () {
        return confirm('¿Quiere cancelar esta solicitud confirmada? Una vez cancelada no quedará disponible para ser pagada');
    });

    $('.pagar').on('click', function () {
        return confirm('¿Quiere pagar esta solicitud pendiente? De ser así, será redirigido para ejecutar el pago de la misma');
    });
    </script>
</body>
</html>