<!DOCTYPE html>
<html>
    <head>
        <!-- Bootstrap -->
        <link href="<?php echo PUBLIC_PATH ?>gentelella/css/bootstrap.min.css" rel="stylesheet">
        <!-- Font Awesome -->
        <link href="<?php echo PUBLIC_PATH ?>gentelella/css/font-awesome.min.css" rel="stylesheet">
        <!-- NProgress -->
        <link href="<?php echo PUBLIC_PATH ?>gentelella/css/nprogress.css" rel="stylesheet">
        <!-- Custom Theme Style -->
        <link href="<?php echo PUBLIC_PATH ?>gentelella/css/custom.min.css" rel="stylesheet">
        <!-- jQuery -->
        <script src="<?php echo PUBLIC_PATH ?>gentelella/css/jquery.min.js"></script>
        <!-- Bootstrap -->
        <script src="<?php echo PUBLIC_PATH ?>gentelella/css/bootstrap.min.js"></script>
        <!-- Datatables -->
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/jquery.dataTables.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/dataTables.bootstrap.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/dataTables.buttons.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/buttons.bootstrap.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/buttons.flash.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/buttons.html5.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/buttons.print.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/jquery.maskedinput.js"></script>
        <!--Import Google Icon Font-->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link type="text/css" rel="stylesheet" href="<?php echo PUBLIC_PATH ?>css/materialize.min.css"  media="screen,projection"/>
        <link type="text/css" rel="stylesheet" href="<?php echo PUBLIC_PATH ?>css/listado.css"  media="screen,projection"/>
        <link rel="stylesheet" type="text/css" href="<?php echo PUBLIC_PATH ?>css/baseFonts.css">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>
    <body>
        <div id="mensajes_flash" >        
            <?php View::content() ?>
        </div> 
        <title>Listado Solicitudes</title>

        <!-- Header con titulo -->
        <nav>
            <div class="nav-wrapper">
                <a href="#" class="brand-logo center">Listado solicitudes</a>
                <a href="#" class="brand-logo left"><?php echo Html::img('logo.png', 'Menu', array("width" => "48px", "height" => "48px")) ?></a>
            </div>
        </nav> 
        <div class="row">
            <ul class="left-align col s6">
                <li><?php echo Html::img('home.png', 'Menu', array("width" => "48px", "height" => "48px")) ?></li>
                <li><?php echo Html::link("ciudadano/", "Menu"); ?></li>
            </ul>
            <ul class="right-align col s6">
                <li><?php echo Html::img('salida.jpg', 'Menu', array("width" => "48px", "height" => "48px")) ?></li>
                <li><?php echo Html::link('admin/index/logout', 'Salir') ?></li>
            </ul>
        </div>
        <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Buscar por nombre propietario..">
        <?php echo Form::close() ?>
        <div class="row">
            <div class="col-sm-12">
                <table class="table table-bordered table-responsive" id="myTable">
                    <thead>
                        <tr>

                            <th>Nombre propietario acta</th>
                            <th>N° de solicitud</th>
                            <th>Parentesco</th>
                            <th>Cupon de pago</th>
                            <th>Tipo libro</th>
                            <th>Fecha solicitud </th>
                            <th>Estado solicitud </th>
                            <th>Eliminar </th>
                            <th>Pagar </th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($listSolicitudacta as $as) { ?>
                            <tr datossolicitud = "<?php echo $as->id ?>">
                                <td><?php echo $as->nombrepropietarioacta ?></td>
                                <td><?php echo $as->id ?></td>
                                <td><?php echo $as->nombreparentesco ?></td>
                                <td><?php echo $as->codigodepago ?></td>
                                <td><?php echo $as->nombrelibro ?></td>
                                <td><?php echo $as->fechacambioestado ?></td>
                                <td><?php echo $as->nombreestadosolicitud ?></td>
                                <?php if ($as->nombreestadosolicitud == "Pendiente de pago") { ?>
                                    <td><a><img alt="" src="<?php echo PUBLIC_PATH ?>img/prohibido2.png"></a></td>    
                                    <td><a><img alt="" src="<?php echo PUBLIC_PATH ?>img/prohibido2.png"></a></td>    
                                <?php } ?> 
                                <?php if ($as->nombreestadosolicitud == "Confirmada") { ?>
                                    <td><a href="<?php echo PUBLIC_PATH . "ciudadano/listado/cancelar/" . $as->id ?>"><img alt="" src="<?php echo PUBLIC_PATH ?>img/figuras/eliminar.png"></a></td>
                                    <td><a href = "<?php echo PUBLIC_PATH . "ciudadano/listado/pagar/" . $as->id ?>" class = 'botonpagar'><img alt="" src="<?php echo PUBLIC_PATH ?>img/figuras/pagar.png"></a></td>
                                        <?php } ?> 
                                        <?php if ($as->nombreestadosolicitud == "Pagada") { ?>
                                    <td><a><img alt="" src="<?php echo PUBLIC_PATH ?>img/prohibido2.png"></a></td>
                                    <td><a><img alt="" src="<?php echo PUBLIC_PATH ?>img/default/valid.png"></a></td>
                                <?php } ?> 
                                <?php if ($as->nombreestadosolicitud == "Cancelada") { ?>
                                    <td><a><img alt="" src="<?php echo PUBLIC_PATH ?>img/prohibido2.png"></a></td>
                                    <td><a><img alt="" src="<?php echo PUBLIC_PATH ?>img/prohibido2.png"></a></td>
                                <?php } ?> 
                                <?php if ($as->nombreestadosolicitud == "Enviada al archivo") { ?>
                                    <td><a><img alt="" src="<?php echo PUBLIC_PATH ?>img/prohibido2.png"></a></td>
                                    <td><a><img alt="" src="<?php echo PUBLIC_PATH ?>img/prohibido2.png"></a></td>
                                <?php } ?> 
                            </tr>
                        <?php } ?>
                    </tbody>
                </table>
            </div>
        </div>
        <script type="text/javascript">
            (function () {
                
            })();

        </script>
        <script>
            $('#myTable tbody tr').on('click', function () {
//                $('#myTable tbody tr').removeClass('seleccion')
//                $(this).addClass('seleccion')
            })
            function myFunction() {
                // Declare variables 
                var input, filter, table, tr, td, i;
                input = document.getElementById("myInput");
                filter = input.value.toUpperCase();
                table = document.getElementById("myTable");
                tr = table.getElementsByTagName("tr");

                // Loop through all table rows, and hide those who don't match the search query
                for (i = 0; i < tr.length; i++) {
                    td = tr[i].getElementsByTagName("td")[0];
                    if (td) {
                        if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
                            tr[i].style.display = "";
                        } else {
                            tr[i].style.display = "none";
                        }
                    }
                }
            }
//            function execute_my_onreturn(json) {
//
//                $.ajax({
//                    url: "<?php echo PUBLIC_PATH ?>ciudadano/index/generar_pdf_firmar_mail",
//                    type: 'post',
//                    data: {
//                        'estado': json.collection_status,
//                        'nrocupon': json.collection_id,
////                        'idsa': $('#myTable tbody tr.seleccion').attr('datossolicitud')
//                    },
//                    success: function (response) {
//                    }
//                });
//                window.open("<?php echo PUBLIC_PATH ?>ciudadano");
//            }
        </script>
    </body>
</html>