<!DOCTYPE html>
<html>

    <head>
        <link rel="stylesheet" type="text/css" href="css/login_style.css">

        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

        <title>CodePen - Random Login Form</title>

        <script src="js/prefixfree.min.js"></script>

    </head>

    <body>

        <div class="body"></div>
        <div class="grad"></div>
        <div class="header">
            <div>INICIAR SESION</div>
        </div>
        <br>
        <?php echo Form::open(NULL, 'post') ?>

        <div class="login">
            <input type="text" placeholder="Usuario" name="login"><br>
            <input type="password" placeholder="Contraseña" name="clave"><br>
            <input type="document" placeholder="DNI" name="document"><br>
            <input type="submit" value="Login">
        </div>
    </form>

    <script src='http://codepen.io/assets/libs/fullpage/jquery.js'></script>

</body>

</html>