<!DOCTYPE html>
<html>
    <head>
        <!-- Bootstrap -->
        <link href="<?php echo PUBLIC_PATH ?>gentelella/css/bootstrap.min.css" rel="stylesheet">
        <!-- Font Awesome -->
        <link href="<?php echo PUBLIC_PATH ?>gentelella/css/font-awesome.min.css" rel="stylesheet">
        <!-- NProgress -->
        <link href="<?php echo PUBLIC_PATH ?>gentelella/css/nprogress.css" rel="stylesheet">
        <!-- Custom Theme Style -->
        <link href="<?php echo PUBLIC_PATH ?>gentelella/css/custom.min.css" rel="stylesheet">
        <!-- jQuery -->
        <script src="<?php echo PUBLIC_PATH ?>gentelella/css/jquery.min.js"></script>
        <!-- Bootstrap -->
        <script src="<?php echo PUBLIC_PATH ?>gentelella/css/bootstrap.min.js"></script>
        <!-- Datatables -->
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/jquery.dataTables.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/dataTables.bootstrap.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/dataTables.buttons.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/buttons.bootstrap.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/buttons.flash.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/buttons.html5.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/buttons.print.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/jquery.maskedinput.js"></script>
        <!--Import Google Icon Font-->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link type="text/css" rel="stylesheet" href="<?php echo PUBLIC_PATH ?>css/materialize.min.css"  media="screen,projection"/>
        <link type="text/css" rel="stylesheet" href="<?php echo PUBLIC_PATH ?>css/listado.css"  media="screen,projection"/>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>
    <?php View::content() ?>
    <title>Actas digitales</title>
    <body>

        <!-- Header con titulo -->
        <nav>
            <div class="nav-wrapper">
                <a href="#" class="brand-logo center">Bienvenido a Actas Digitales - <?php echo Auth::get('nombres'); ?></a>
            </div>
        </nav>  
        <div class="center">
            <div class="nav-wrapper">
                <ul class="right-align col s6">
                    <li><?php echo Html::img('salida.jpg', 'Menu', array("width" => "48px", "height" => "48px")) ?></li>
                    <li><?php echo Html::link('admin/index/logout', 'Salir') ?></li>
                </ul>
            </div>
            <div class="nav-wrapper">
                <tr>
                    <td><?php echo Html::img('Crear_Solicitud.png', 'Crear_Solicitud', array("width" => "128px", "height" => "128px")) ?></td>
                    <td><?php echo Html::link("ciudadano/solicitud/", "Crear Solicitud"); ?></td>
                </tr>
            </div>
            <br>
            <div class="nav-wrapper">
                <tr>
                    <td><?php echo Html::img('Actas Caducadas.png', 'Solicitudes', array("width" => "128px", "height" => "128px")) ?></td>
                    <td><?php echo Html::link("ciudadano/listado/", "Mis solicitudes"); ?></td>
                </tr>
            </div>
            <br>
            <div class="nav-wrapper">
                <tr>
                    <td><?php echo Html::img('verificar.png', 'Verificar_validez', array("width" => "128px", "height" => "128px")) ?></td>
                    <td><?php echo Html::link("ciudadano/verificar/", "Verificar validez"); ?></td>
                </tr>
            </div>
        </div>

        <!--Import jQuery before materialize.js-->
        <script type="text/javascript" src="<?php echo PUBLIC_PATH ?>js/jquery-3.2.1.min.js"></script>
        <script type="text/javascript" src="<?php echo PUBLIC_PATH ?>js/materialize.min.js"></script>
        <script type="text/javascript" src="<?php echo PUBLIC_PATH ?>js/init.js"></script>
    </body>
</html>