<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <title>Gestión de Actas Digitales</title>
        <!-- Bootstrap -->
        <link href="<?php echo PUBLIC_PATH ?>gentelella/css/bootstrap.min.css" rel="stylesheet">
        <!-- Bootstrap -->
        <script src="<?php echo PUBLIC_PATH ?>gentelella/css/bootstrap.min.js"></script>
        <!-- CSS  -->
        <link href="<?php echo PUBLIC_PATH ?>css/fuentes.css" type="text/css" rel="stylesheet">
        <link href="<?php echo PUBLIC_PATH ?>css/materialize.css" type="text/css" rel="stylesheet" media="screen,projection"/>
        <link href="<?php echo PUBLIC_PATH ?>css/style.css" type="text/css" rel="stylesheet" media="screen,projection"/>

    </head>
    <body>
        <nav class="nav-extended">
            <div class="nav-wrapper">
                <div class="nav-container">
                    <a href="#" class="brand-logo__link"><?php echo Html::img('logo.png', 'Menu', array("width" => "48px", "height" => "48px")) ?></a>
                    <?php echo Html::link("", "<div class=\"header-logo\">GESTIÓN DE ACTAS DIGITALES</div>"); ?>
                </div>
            </div>
        </nav>

        <div id="index-banner" class="parallax-container">
            <div class="section no-pad-bot">
                <div class="container">
                    <br><br>
                    <h1 class="header center col s12" id="title">Tus actas digitales de forma rápida y segura</h1>
                    <div class="row center">
                        <h5 class="header col s12 light">La forma más rápida de sacar tus actas de forma digital y en la comodidad de tu hogar</h5>
                    </div>
                    <br><br>
                    <!--   Boton de iniciar sesion   -->
                    <div class="row center">
                        <?php echo html::link('login', "Inicia sesión", array("class" => "btn-large waves-effect waves blue darken-3", "id" => "download-button", "style" => "width: 335px;")) ?>
                        <br><br>
                        <span></span>
                        <br><br>
                        <?php echo html::link('verificarentidad', "Verifica la validez de tu acta", array("class" => "btn-large waves-effect waves blue darken-3", "id" => "download-button", "style" => "width: 335px;")) ?>
                        <div class="row right-align" style="display: flex; align-items: center; justify-content: center">
                            <i style="margin-right: 5px; font-size: 20px" class="large material-icons">local_library</i>
                            <a href="<?php echo PUBLIC_PATH ?>default/public/Manual de Usuario.pdf" target="_blank">Manual de usuario </a>
                        </div>

                    </div>
                </div>
            </div>
            <div class="parallax cropper"><img style="filter: hue-rotate(230deg) grayscale(40%);" src="<?php echo PUBLIC_PATH ?>img/background123.jpg" alt="Unsplashed background img 1"></div>
        </div>
        <div class="container">
            <div class="section">

                <!--   Icon Section   -->
                <div class="row">
                    <div class="col s12 m4">
                        <div class="icon-block">
                            <h2 class="center"><i class="material-icons">flash_on</i></h2>
                            <h5 class="center">Con esta aplicación evitaras...</h5>

                            <p class="light">...ir innecesariamente a un registro civil u oficina del gobierno para realizar el tramite presencial</p>
                        </div>
                    </div>

                    <div class="col s12 m4">
                        <div class="icon-block">
                            <h2 class="center"><i class="material-icons">group</i></h2>
                            <h5 class="center">Te ofrecemos...</h5>

                            <p class="light">...mucha facilidad de uso, sencillez y es 100% eficiente, disponible para toda persona que quiera hacer uso de la aplicación</p>
                        </div>
                    </div>

                    <div class="col s12 m4">
                        <div class="icon-block">
                            <h2 class="center"><i class="material-icons">settings</i></h2>
                            <h5 class="center">Además...</h5>
                            <p class="light">...te ahorramos mucho tiempo malgastado y evitamos cualquier tipo de fraude posible.</p>
                        </div>
                    </div>
                </div>

            </div>
        </div>


        <div class="parallax-container valign-wrapper">
            <div class="section no-pad-bot">
                <div class="container">
                    <div class="row center">
                        <!--<h5 class="header col s12 ">Una solucion ágil, tecnológica e innovadora para sacar tus actas de nacimiento, matrimonio, defunción o union convivencial</h5>-->
                    </div>
                </div>
            </div>
            <div class="parallax cropper"><img src="<?php echo PUBLIC_PATH ?>img/2.jpg" alt="Unsplashed background img 2"></div>
        </div>

        <div class="container">
            <div class="section">

                <div class="row">
                    <div class="col s12 center">
                        <h3><i class="mdi-content-send brown-text"></i></h3>
                        <h4>Algo de nosotros</h4>
                        <p class="left-align light">Somos un grupo de 4 estudiantes enfocándonos en este proyecto como nuestra tesis final de grado. Buscamos como objetivo proporcionar un servicio totalmente funcional a los ciudadanos para hacerles cualquier tarea, involucrada con la tematica principal de este sitio, mucho mas sencilla y cómoda de realizar.</p>
                    </div>
                </div>

            </div>
        </div>

        <footer class="page-footer center blue darken-3" style="display: flex; align-items: center; justify-content: center; padding: 20px">
            Hecho por Equipo 6 - UTN FRM
        </footer>


        <!--  Scripts-->
        <script src="<?php echo PUBLIC_PATH ?>js/jquery-3.2.1.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>js/materialize.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>js/init.js"></script>

    </body>
</html>
