<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <title>Gestion de Actas Digitales</title>

        <!-- CSS  -->
        <link href="<?php echo PUBLIC_PATH ?>css/fuentes.css" type="text/css" rel="stylesheet">
        <link href="<?php echo PUBLIC_PATH ?>css/materialize.css" type="text/css" rel="stylesheet" media="screen,projection"/>
        <link href="<?php echo PUBLIC_PATH ?>css/style.css" type="text/css" rel="stylesheet" media="screen,projection"/>
    </head>
    <body>
        <nav class="nav-extended">
            <div class="nav-wrapper">
                <div href="#" class="brand-logo center"><a>GESTION DE ACTAS DIGITALES</a></div>
            </div>
        </nav>

        <div id="index-banner" class="parallax-container">
            <div class="section no-pad-bot">
                <div class="container">
                    <br><br>
                    <h1 class="header center col s12" id="title">Tus actas digitales de forma rápida y segura!</h1>
                    <div class="row center">
                        <h5 class="header col s12 light">La forma mas rapida de sacar tus actas de forma digital y en la comodidad de tu hogar</h5>
                    </div>
                    <br><br>
                    <!--   Boton de iniciar sesion   -->
                    <div class="row center">
                        <?php echo html::link('admin', "HAGA CLICK AQUI PARA EMPEZAR", array("class" => "btn-large waves-effect waves", "id" => "download-button")) ?>
                        <div class="section"><?php echo view::content() ?></div>
                    </div>


                </div>
            </div>
            <div class="parallax cropper"><img src="<?php echo PUBLIC_PATH ?>img/background123.jpg" alt="Unsplashed background img 1"></div>
        </div>
        <div class="container">
            <div class="section">

                <!--   Icon Section   -->
                <div class="row">
                    <div class="col s12 m4">
                        <div class="icon-block">
                            <h2 class="center"><i class="material-icons">flash_on</i></h2>
                            <h5 class="center">Con esta aplicación evitaras...</h5>

                            <p class="light">...ir innecesariamente a un registro civil u oficina del gobierno para realizar el tramite presencial</p>
                        </div>
                    </div>

                    <div class="col s12 m4">
                        <div class="icon-block">
                            <h2 class="center"><i class="material-icons">group</i></h2>
                            <h5 class="center">Te ofrecemos...</h5>

                            <p class="light">...mucha facilidad de uso, sencillez y es 100% eficiente, disponible para toda persona que quiera hacer uso de la aplicación</p>
                        </div>
                    </div>

                    <div class="col s12 m4">
                        <div class="icon-block">
                            <h2 class="center"><i class="material-icons">settings</i></h2>
                            <h5 class="center">Además...</h5>
                            <p class="light">...te ahorramos mucho tiempo malgastado y evitamos cualquier tipo de fraude posible.</p>
                        </div>
                    </div>
                </div>

            </div>
        </div>


        <div class="parallax-container valign-wrapper">
            <div class="section no-pad-bot">
                <div class="container">
                    <div class="row center">
                        <!--<h5 class="header col s12 ">Una solucion ágil, tecnológica e innovadora para sacar tus actas de nacimiento, matrimonio, defunción o union convivencial</h5>-->
                    </div>
                </div>
            </div>
            <div class="parallax cropper"><img src="<?php echo PUBLIC_PATH ?>img/2.jpg" alt="Unsplashed background img 2"></div>
        </div>

        <div class="container">
            <div class="section">

                <div class="row">
                    <div class="col s12 center">
                        <h3><i class="mdi-content-send brown-text"></i></h3>
                        <h4>Algo de nosotros</h4>
                        <p class="left-align light">Somos un grupo de 4 estudiantes enfocandonos en este proyecto como nuestra tesis final de grado. Buscamos como objetivo proporcionar un servicio totalmente funcional a los ciudadanos para hacerles cualquier tarea, involucrada con la tematica principal de este sitio, mucho mas sencilla y cómoda de realizar.</p>
                    </div>
                </div>

            </div>
        </div>

        <footer class="page-footer">
            <!--    <div class="container">
                  <div class="row">
                    <div class="col l3 s12">
                      <h5 class="white-text">Settings</h5>
                      <ul>
                        <li><a class="white-text" href="#!">Link 1</a></li>
                        <li><a class="white-text" href="#!">Link 2</a></li>
                        <li><a class="white-text" href="#!">Link 3</a></li>
                        <li><a class="white-text" href="#!">Link 4</a></li>
                      </ul>
                    </div>
                    <div class="col l3 s12">
                      <h5 class="white-text">Connect</h5>
                      <ul>
                        <li><a class="white-text" href="#!">Link 1</a></li>
                        <li><a class="white-text" href="#!">Link 2</a></li>
                        <li><a class="white-text" href="#!">Link 3</a></li>
                        <li><a class="white-text" href="#!">Link 4</a></li>
                      </ul>
                    </div>
                  </div>
                </div>-->
            <div class="footer-copyright">
                <div class="container">
                    Hecho por <a href="#!">    Equipo 6 - UTN FRM</a>
                </div>
            </div>
        </footer>


        <!--  Scripts-->
        <script src="<?php echo PUBLIC_PATH ?>js/jquery-3.2.1.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>js/materialize.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>js/init.js"></script>

    </body>
</html>
