<!DOCTYPE html>
<html>
    <head>
        <!--Import Google Icon Font-->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link type="text/css" rel="stylesheet" href="<?php echo PUBLIC_PATH ?>css/materialize.min.css"  media="screen,projection"/>
        <link type="text/css" rel="stylesheet" href="<?php echo PUBLIC_PATH ?>css/listado.css"  media="screen,projection"/>
        <link rel="stylesheet" href="<?php echo PUBLIC_PATH ?>css/alerta.css">
        <link rel="stylesheet" type="text/css" href="<?php echo PUBLIC_PATH ?>css/registro.css">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>
    <?php View::content() ?>
    <title>Actas digitales</title>
    <body>

        <!-- Header con titulo -->
        <nav>
            <div class="nav-wrapper">
                <a href="#" class="brand-logo center">Rectificar datos</a>
            </div>
        </nav>  
        <div class="row">
            <ul class="left-align col s6">
                <li><?php echo Html::img('home.png', 'Menu', array("width" => "48px", "height" => "48px")) ?></li>
                <li><?php echo Html::link("ciudadano/", "Menu"); ?></li>
            </ul>
            <ul class="right-align col s6">
                <li><?php echo Html::img('salida.jpg', 'Menu', array("width" => "48px", "height" => "48px")) ?></li>
                <li><?php echo Html::link('admin/index/logout', 'Salir') ?></li>
            </ul>
        </div>
        <div class="row center">
            <h5 class="header col s12 light">Completá los datos que hay que rectificar</h5>
        </div>
        <div class="center row">
            <form class="col s12"> 
                <div class="row">
                    <div class="input-field">
                        <input id="anioacta" placeholder="Año acta" type="text">
                        <label for="anioacta">Año acta</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field">
                        <input id="nroacta" placeholder="número acta" type="text">
                        <label for="nroacta">Número acta</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field">
                        <input id="nrolibro" placeholder="número libro" type="text">
                        <label for="nrolibro">Número libro</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field">
                        <input id="nombre" placeholder="Nombre titular" type="text">
                        <label for="nombre">Nombre titular</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field">
                        <input id="apellido" placeholder="Apellido titular" type="text">
                        <label for="apellido">Apellido titular</label>
                    </div>
                </div>
                <button id="submitButton" class="btn waves-effect waves-light" disabled="disabled" type="submit" name="action">Enviar informe de error
                    <i class="material-icons right">send</i>
                </button>
                <div class="row" id="rta">
                </div>
            </form>
        </div>
        <!--Import jQuery before materialize.js-->
        <script type="text/javascript" src="<?php echo PUBLIC_PATH ?>js/jquery-3.2.1.min.js"></script>
        <script type="text/javascript" src="<?php echo PUBLIC_PATH ?>js/materialize.min.js"></script>
        <script type="text/javascript" src="<?php echo PUBLIC_PATH ?>js/init.js"></script>
    </body>
</html>