<!DOCTYPE html>
<html>
    <head>
        <!-- Bootstrap -->
        <link href="<?php echo PUBLIC_PATH ?>gentelella/css/bootstrap.min.css" rel="stylesheet">
        <!-- Font Awesome -->
        <link href="<?php echo PUBLIC_PATH ?>gentelella/css/font-awesome.min.css" rel="stylesheet">
        <!-- NProgress -->
        <link href="<?php echo PUBLIC_PATH ?>gentelella/css/nprogress.css" rel="stylesheet">
        <!-- Custom Theme Style -->
        <link href="<?php echo PUBLIC_PATH ?>gentelella/css/custom.min.css" rel="stylesheet">
        <!-- jQuery -->
        <script src="<?php echo PUBLIC_PATH ?>gentelella/css/jquery.min.js"></script>
        <!-- Bootstrap -->
        <script src="<?php echo PUBLIC_PATH ?>gentelella/css/bootstrap.min.js"></script>
        <!-- Datatables -->
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/jquery.dataTables.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/dataTables.bootstrap.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/dataTables.buttons.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/buttons.bootstrap.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/buttons.flash.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/buttons.html5.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/buttons.print.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/jquery.maskedinput.js"></script>
        <!--Import Google Icon Font-->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <!--Import materialize.css-->
        <link type="text/css" rel="stylesheet" href="<?php echo PUBLIC_PATH ?>css/materialize.min.css"  media="screen,projection"/>
        <link rel="stylesheet" type="text/css" href="<?php echo PUBLIC_PATH ?>css/registro.css">
        <link rel="stylesheet" type="text/css" href="<?php echo PUBLIC_PATH ?>css/alerta.css">
        <link rel="stylesheet" type="text/css" href="<?php echo PUBLIC_PATH ?>css/baseFonts.css">

        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>
    <title>Registro de usuario</title>
    <body>

        <!-- Header con titulo -->
        <nav>
            <div class="nav-wrapper">
                <a href="#" class="brand-logo center">Registro de usuario</a>
                <a href="/Users/gaston/Desktop/githubProyecto/Proy-Final-Documentacion/proyecto/default/public/img/logo.jpg" class="brand-logo"></a>
            </div>
        </nav>  

        <!-- Formato del formulario con boton al final -->
        <div class="center row">
            <form> 
                <div class="row"> 
                    <div class="input-field">
                        <!-- input numerico tratado como texto para resolver el problema de type="number" no reconoce el atributo maxlenght -->
                        <input id="numero_documento" placeholder="Numero documento" type="text" class="validate" pattern="\d*" maxlength="8">
                        <label for="numero_documento" data-error="Documento no valido" data-success="Documento Valido">Nº documento</label>  
                    </div>
                </div>
                <div class="row"> 
                    <div class="input-field">
                        <input id="numero_tramite" placeholder="Numero tramite" type="text" class="validate" pattern="\d*">
                        <label for="numero_tramite" data-error="Numero de tramite inválido" data-success="Numero de tramite válido">Nº tramite</label>
                    </div>
                    <div class="separateWithTop">
                        <td><?php echo Html::img('dni1.1.png', 'Crear_Solicitud', array("width" => "310px", "height" => "160px")) ?></td>
                    </div>
                    <div class="separateWithTop">
                        <td><?php echo Html::img('dni2.2.png', 'Crear_Solicitud', array("width" => "310px", "height" => "160px")) ?></td>
                    </div>  
                </div>
                <div class="row">
                    <div class="input-field">
                        <input id="nombres" placeholder="Nombres" type="text" disabled="disabled">
                        <label for="nombres">Nombres</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field">
                        <input id="apellido" placeholder="Apellido" type="text" disabled="disabled">
                        <label for="apellido">Apellido</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field" id="provincia">
                        <?php echo Form::dbselect('departamento.idprovincia', 'nombreprovincia', array('provincia', 'find')) ?>
                        <label>Seleccion Provincia</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field" id="departamento">
                        <select id="select_dpto">
                            <option value="" disabled selected>Seleccione</option>
                        </select>
                        <label>Seleccion Departamento</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field" id="localidad">
                        <select id="select_localidad">
                            <option value="" disabled selected>Seleccione</option>
                        </select>
                        <label>Seleccion Localidad</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field">
                        <input id="domicilio" placeholder="Domicilio" type="text">
                        <label for="domicilio">Domicilio</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field">
                        <input id="nombre_usuario" placeholder="Nombre Usuario" type="text" class="validate">
                        <label for="nombre_usuario" data-error="Prueba otro nombre de usuario" data-success="Usuario valido" >Nombre de Usuario</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field">
                        <input id="contraseña" placeholder="contraseña" type="password" class="validate">
                        <label for="contraseña" data-error="Password invalido" data-success="Contraseña valida">contraseña</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field">
                        <input id="repetir_contraseña" placeholder="repetir contraseña" type="password">
                        <label for="repetir_contraseña" data-error="Contraseñas no coinciden" data-success="Contraseñas coinciden">repetir contraseña</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field">
                        <input id="email" placeholder="Email" type="email" class="validate">
                        <label for="email" data-error="Mail inválido" data-success="right">Email</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field">
                        <select>
                            <option value="" disabled selected>Seleccion tipo nº telefono</option>
                            <option value="1">Telefono fijo</option>
                            <option value="2">Telefono celular</option>
                        </select>
                        <label>Tipo Numero Telefono</label>
                    </div>
                </div>

                <div class="row"> 
                    <div class="input-field">
                        <input id="numero_telefono" placeholder="Numero telefono" type="tel" class="validate" pattern="\d*" maxlength="10">
                        <label for="numero_telefono" data-error="Numero de telefono inválido" data-success="Numero de telefono válido">Nº telefono</label>
                    </div>
                </div>
                <input id="condiciones" type="checkbox"/> 
                <label for="condiciones">  <a href="<?php echo PUBLIC_PATH ?>tyc" target="_blank"> Acepta los términos y condiciones</a></label>
                <!-- El boton esta deshabilitado. Para habilitarlo solo hay que reomver disable de la clase -->
                <br>
                <button id="submitButton" class="btn waves-effect waves-light" disabled="disabled" type="submit" name="action">Crear
                    <i class="material-icons right">send</i>
                </button>
                <div class="row" id="rta">
                </div>
            </form>
        </div>

    </div>

    <!--Import jQuery before materialize.js-->
    <script type="text/javascript" src="<?php echo PUBLIC_PATH ?>js/jquery-3.2.1.min.js"></script>
    <script type="text/javascript" src="<?php echo PUBLIC_PATH ?>js/materialize.min.js"></script>
    <script type="text/javascript" src="<?php echo PUBLIC_PATH ?>js/jquery/jquery.kumbiaphp.js"></script>
    <!-- En init.js esta declarada la inicializacion del selector que se utiliza en tipo nro telefono-->
    <script src="<?php echo PUBLIC_PATH ?>js/init.js"></script>
    <!-- En registroUsuario.js declarada toda la logica pertinente al registro del usuario. Tambien esta la funcion que evita que se agregue la letra
    "e" en los input fields de tipo number-->
    <script>
        $(function () {
            $("#numero_documento").keypress(function (event) {
                if (event.which != 8 && event.which != 0 && (event.which < 48 || event.which > 57)) {
                    alert("Solo puede ingresar numeros!");
                    return false;
                }
            });
        });

//Evitar introducir letras en numero de telefono
        $(function () {
            $("#numero_telefono").keypress(function (event) {
                if (event.which != 8 && event.which != 0 && (event.which < 48 || event.which > 57)) {
                    alert("Solo puede ingresar numeros!");
                    return false;
                }
            });
        });

//Evitar introducir letras en numero de telefono
        $(function () {
            $("#numero_tramite").keypress(function (event) {
                if (event.which != 8 && event.which != 0 && (event.which < 48 || event.which > 57)) {
                    alert("Solo puede ingresar numeros!");
                    return false;
                }
            });
        });

//habilitar o deshabilitar boton submit hasta que los campos esten completos
        (function () {
            $('form input').keyup(function () {

                var empty = false;
                $('form input').each(function () {
                    if ($(this).val() == '') {
                        empty = true;
                    }
                });
                if (empty || !$("#condiciones").is(":checked")) {
                    $('#submitButton').attr('disabled', 'disabled'); // updated according to http://stackoverflow.com/questions/7637790/how-to-remove-disabled-attribute-with-jquery-ie
                } else {
                    $('#submitButton').removeAttr('disabled'); // updated according to http://stackoverflow.com/questions/7637790/how-to-remove-disabled-attribute-with-jquery-ie
                }
            });
            $("#condiciones").click(function () {
                $('form input').keyup()
            })
        })()

//auto carga del nombre de la persona segun el DNI y el numero tramite introducido
        $("#numero_tramite").change(function () {
            if (($("#numero_tramite").val() != "") && ($("#numero_documento").val() != "")) {
                $("#nombres").val("");

                $("#apellido").val("");

                $.ajax({
                    data: {
                        'idtramite': $("#numero_tramite").val(),
                        'dni': $("#numero_documento").val()
                    },
                    url: "<?php echo PUBLIC_PATH ?>tramitedni/buscar_ciudadano_por_id_dni",
                    type: 'post',
                    dataType: "json",
                    success: function (response) {
                        if (response) {
                            $("#nombres").removeAttr("readonly");
                            $("#nombres").removeAttr("disabled");
                            $("#nombres").val(response.nombres);

                            $("#apellido").removeAttr("readonly");
                            $("#apellido").removeAttr("disabled");
                            $("#apellido").val(response.apellido);
                        } else {
                            alert("Revisar DNI y numero de tramite");
                        }
                        $("#nombres").attr("readonly", "readonly");
                        $("#apellido").attr("readonly", "readonly")
                    }
                });
            }
        });

        $("#numero_documento").change(function () {
            if (($("#numero_tramite").val() != "") && ($("#numero_documento").val() != "")) {
                $("#nombres").val("");

                $("#apellido").val("");

                $.ajax({
                    data: {
                        'idtramite': $("#numero_tramite").val(),
                        'dni': $("#numero_documento").val()
                    },
                    url: "<?php echo PUBLIC_PATH ?>tramitedni/buscar_ciudadano_por_id_dni",
                    type: 'post',
                    dataType: "json",
                    success: function (response) {
                        if (response) {
                            $("#nombres").removeAttr("readonly");
                            $("#nombres").removeAttr("disabled");
                            $("#nombres").val(response.nombres);

                            $("#apellido").removeAttr("readonly");
                            $("#apellido").removeAttr("disabled");
                            $("#apellido").val(response.apellido);
                        } else {
                            alert("Revisar DNI y numero de tramite");
                        }
                        $("#apellido").attr("readonly", "readonly")
                        $("#nombres").attr("readonly", "readonly");
                    }
                });
            }
        });

        $("#repetir_contraseña").change(function () {
            var contraseña = $("#contraseña").val();
            var repetida = $("#repetir_contraseña").val();

            if (contraseña != repetida) {
                $("#repetir_contraseña").removeClass("valid");
                $("#repetir_contraseña").addClass("invalid");
                $("#repetir_contraseña").prop("aria-invalid", "false");
            } else {
                $("#repetir_contraseña").removeClass("invalid");
                $("#repetir_contraseña").addClass("valid");
                $("#repetir_contraseña").prop("aria-valid", "false");
            }
        });


//Poblar select departamento segun la provincia seleccionada
        $("#provincia").change(function () {
            $.ajax({
                data: {
                    'provincia': $(this).find(':selected').val()
                },
                type: "POST",
                url: "<?php echo PUBLIC_PATH ?>departamento/Depto_segun_provincia",
                success: function (response) {
                    var jsonObj = JSON.parse(response);

                    //Alert utilizada para ver la cantidad de elementos que devuelve el server
                    //alert(jsonObj.items.length);

                    $('#select_dpto')
                            .find('option')
                            .remove()
                            .end()
                            .append('<option disabled value="option">Seleccione</option>')
                            .val('whatever')
                            ;

                    $('#select_localidad')
                            .find('option')
                            .remove()
                            .end()
                            .append('<option disabled value="option">Seleccione</option>')
                            .val('whatever')
                            ;

                    $.each(jsonObj.items, function (id, value) {
                        $("#select_dpto").append('<option value="' + value.id + '">' + value.nombredepartamento + '</option>');
                    })
                    $("#select_dpto").material_select();
                    $("#select_localidad").material_select();
                }
            });
        });

//Poblar select localidad segun el departamento seleccionado
        $("#departamento").change(function () {
            console.log($(this).find(':selected').text());
            console.log($(this).find(':selected').val());
            $.ajax({
                data: {
                    'departamento': $(this).find(':selected').val()
                },
                type: "POST",
                url: "<?php echo PUBLIC_PATH ?>localidad/localidad_segun_dpto",
                success: function (response) {
                    var jsonObj = JSON.parse(response);

                    //Alert utilizada para ver la cantidad de elementos que devuelve el server
                    //alert(jsonObj.items.length);

                    $('#select_localidad')
                            .find('option')
                            .remove()
                            .end()
                            .append('<option disabled value="option">Seleccione</option>')
                            .val('whatever')
                            ;

                    $.each(jsonObj.items, function (id, value) {
                        $("#select_localidad").append('<option value="' + value.id + '">' + value.nombrelocalidad + '</option>');
                    })
                    $("#select_localidad").material_select();
                }
            });
        });

//para definir que funcionalidad tiene el boton submit (crear usuario)
        $("#submitButton").click(function (evt) {
            evt.preventDefault();
            var usuarioForm = {
                'login': $("#nombre_usuario").val(),
                'clave': $("#contraseña").val(),
                'clave2': $("#repetir_contraseña").val(),
                'idtramite': $("#numero_tramite").val(),
                'dni': $("#numero_documento").val(),
                'nombres': $("#nombres").val(),
                'apellido': $("#apellido").val(),
                'email': $("#email").val(),
            };

            $.ajax({
                data: {
                    'usuario': usuarioForm
                },
                url: "<?php echo PUBLIC_PATH ?>usuarios/crear",
                type: 'POST',
                success: function (response) {
                    alert("exito");
                    window.open('login')
                },
                error: function (response) {
                    $("#rta").html(response.responseText);
                }
            });
        });
    </script>
</body>
</html>
