  <!DOCTYPE html>
  <html>
    <head>
      <!--Import Google Icon Font-->
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <!--Import materialize.css-->
      <link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen,projection"/>
      <link rel="stylesheet" type="text/css" href="css/registro.css">

      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>
    <title>Registro de usuario</title>
    <body>

      <!-- Header con titulo -->
      <nav>
        <div class="nav-wrapper">
        <a href="#" class="brand-logo center">Registro de usuario</a>
        </div>
      </nav>  

      <!-- Formato del formulario con boton al final -->
      <div class="center row">
         <form class="col s12"> 
            <div class="row"> 
              <div class="input-field">
                <!-- input numerico tratado como texto para resolver el problema de type="number" no reconoce el atributo maxlenght -->
                <input id="numero_documento" placeholder="Numero documento" type="text" class="validate" pattern="\d*" maxlength="8">
                <label for="numero_documento" data-error="Documento no valido" data-success="Documento Valido">Nº documento</label>  
              </div>
            </div>
            <div class="row"> 
              <div class="input-field">
                <input id="numero_tramite" placeholder="Numero tramite" input type="text" class="validate" pattern="\d*">
                <label for="numero_tramite" data-error="Numero de tramite inválido" data-success="Numero de tramite válido">Nº tramite</label>
              </div>
            </div>
            <div class="row">
              <div class="input-field">
                <input id="nombres" placeholder="Nombres" type="text">
                <label for="nombres">Nombres</label>
              </div>
            </div>
            <div class="row">
              <div class="input-field" id="provincia">
                <?php echo Form::dbselect('departamento.idprovincia', 'nombreprovincia', array('provincia','find')) ?>
                <label>Seleccion Provincia</label>
              </div>
            </div>
            <div class="row">
              <div class="input-field" id="departamento">
                <select id="select_dpto"></select>
                <label>Seleccion Departamento</label>
              </div>
            </div>
            <div class="row">
              <div class="input-field" id="localidad">
                <select id="select_localidad"></select>
                <label>Seleccion Localidad</label>
              </div>
            </div>
            <div class="row">
              <div class="input-field">
                <input id="domicilio" placeholder="Domicilio" type="text">
                <label for="domicilio">Domicilio</label>
              </div>
            </div>
            <div class="row">
              <div class="input-field">
                <input id="nombre_usuario" placeholder="Nombre Usuario" type="text" class="validate">
                <label for="nombre_usuario" data-error="Prueba otro nombre de usuario" data-success="Usuario valido" >Nombre de Usuario</label>
              </div>
            </div>
            <div class="row">
              <div class="input-field">
                <input id="contraseña" placeholder="contraseña" type="password" class="validate">
                <label for="contraseña" data-error="Password invalido" data-success="Password valido">contraseña</label>
              </div>
            </div>
            <div class="row">
              <div class="input-field">
                <input id="repetir_contraseña" placeholder="repetir contraseña" type="password" class="validate">
                <label for="repetir_contraseña" data-error="Contraseñas no coinciden" data-success="Contraseñas coinciden">repetir contraseña</label>
              </div>
            </div>
            <div class="row">
              <div class="input-field">
                <input id="email" placeholder="Email" type="email" class="validate">
                <label for="email" data-error="Mail inválido" data-success="right">Email</label>
              </div>
            </div>
            <div class="row">
              <div class="input-field">
                <select>
                  <option value="" disabled selected>Seleccion tipo nº telefono</option>
                  <option value="1">Telefono fijo</option>
                  <option value="2">Telefono celular</option>
                </select>
                <label>Tipo Numero Telefono</label>
              </div>
            </div>
            <div class="row"> 
              <div class="input-field">
                <input id="numero_telefono" placeholder="Numero telefono" input type="text" class="validate" pattern="\d*">
                <label for="numero_telefono" data-error="Numero de telefono inválido" data-success="Numero de telefono válido">Nº telefono</label>
              </div>
            </div>
            <!-- El boton esta deshabilitado. Para habilitarlo solo hay que reomver disable de la clase -->
            <button id="submitButton" class="btn waves-effect waves-light" disabled="disabled" type="submit" name="action">Submit
            <i class="material-icons right">send</i>
          </button>
          </form>
        </div>

        </div>

      <!--Import jQuery before materialize.js-->
      <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
      <script type="text/javascript" src="js/materialize.min.js"></script>
      <script type="text/javascript" src="js/jquery/jquery.kumbiaphp.js"></script>
       <!-- En init.js esta declarada la inicializacion del selector que se utiliza en tipo nro telefono-->
      <script src="js/init.js"></script>
       <!-- En registroUsuario.js declarada toda la logica pertinente al registro del usuario. Tambien esta la funcion que evita que se agregue la letra
       "e" en los input fields de tipo number-->
      <script src="js/registroUsuario.js"></script>
    </body>
  </html>
        