<!DOCTYPE html>
<html>
    <head>
        <!-- Bootstrap -->
        <link href="<?php echo PUBLIC_PATH ?>gentelella/css/bootstrap.min.css" rel="stylesheet">
        <!-- Font Awesome -->
        <link href="<?php echo PUBLIC_PATH ?>gentelella/css/font-awesome.min.css" rel="stylesheet">
        <!-- NProgress -->
        <link href="<?php echo PUBLIC_PATH ?>gentelella/css/nprogress.css" rel="stylesheet">
        <!-- Custom Theme Style -->
        <link href="<?php echo PUBLIC_PATH ?>gentelella/css/custom.min.css" rel="stylesheet">
        <!-- jQuery -->
        <script src="<?php echo PUBLIC_PATH ?>gentelella/css/jquery.min.js"></script>
        <!-- Bootstrap -->
        <script src="<?php echo PUBLIC_PATH ?>gentelella/css/bootstrap.min.js"></script>
        <!-- Datatables -->
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/jquery.dataTables.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/dataTables.bootstrap.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/dataTables.buttons.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/buttons.bootstrap.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/buttons.flash.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/buttons.html5.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/buttons.print.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/jquery.maskedinput.js"></script>
        <!--Import Google Icon Font-->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link type="text/css" rel="stylesheet" href="<?php echo PUBLIC_PATH ?>css/materialize.min.css"  media="screen,projection"/>
        <link type="text/css" rel="stylesheet" href="<?php echo PUBLIC_PATH ?>css/listado.css"  media="screen,projection"/>
        <link rel="stylesheet" href="<?php echo PUBLIC_PATH ?>css/alerta.css">
        <link rel="stylesheet" href="<?php echo PUBLIC_PATH ?>css/registro.css">
        <link rel="stylesheet" href="<?php echo PUBLIC_PATH ?>css/baseFonts.css">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>
    <?php View::content() ?>
    <title>Actas digitales</title>
    <body>

        <!-- Header con titulo -->
        <nav>
            <div class="nav-wrapper">
                <a href="#" class="brand-logo center">Reportar error </a>
            </div>
        </nav>  
        <div class="row">
            <ul class="left-align col s6">
                <li><?php echo Html::img('home.png', 'Menu', array("width" => "48px", "height" => "48px")) ?></li>
                <li><?php echo Html::link("ciudadano/", "Menu"); ?></li>
            </ul>
            <ul class="right-align col s6">
                <li><?php echo Html::img('salida.jpg', 'Menu', array("width" => "48px", "height" => "48px")) ?></li>
                <li><?php echo Html::link('admin/index/logout', 'Salir') ?></li>
            </ul>
        </div>
        <div class="center row">
            <?php echo Form::open('ciudadano/reportarerror/crear_reclamo', 'post') ?>
            <div class="row ">
                <label>Selecciona el tipo de error y completá los datos</label>
                <div class="input-field">
                    <?php echo Form::dbselect('tiporeclamo.idtiporeclamo', 'nombretiporeclamo', array('tiporeclamo', 'find')) ?>
                </div>
            </div>
            <div class="row">
                <div class="input-field">
                    <?php echo Form::text('tiporeclamo.numeroacta') ?>
                    <!--<input id="nroacta" placeholder="número acta" type="text">-->
                    <label for="nroacta">Número acta</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field">
                    <?php echo Form::text('tiporeclamo.numerolibro') ?>
                    <!--<input id="nrolibro" placeholder="número libro" type="text">-->
                    <label for="nrolibro">Número libro</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field">
                    <?php echo Form::text('tiporeclamo.nombrepropietarioacta') ?>
                    <!--<input id="nombre" placeholder="Nombre titular" type="text">-->
                    <label for="nombre">Nombre titular</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field">
                    <?php echo Form::text('tiporeclamo.apellidopropietarioacta') ?>
                    <!--<input id="apellido" placeholder="Apellido titular" type="text">-->
                    <label for="apellido">Apellido titular</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field">
                    <?php echo Form::textarea('tiporeclamo.observaciones', 'rows="10" cols="40"') ?>
                    <!--<textarea id="comentarios" name="comentarios" rows="10" cols="40">Escribe aquí tus comentarios</textarea>-->
                    <label for="comentarios">Escribe aquí tus comentarios</label>
                </div>
            </div>
            <div class="center">
                <button class="btn-large waves-effect waves-light btn" type="submit" value="Verificar" id="boton1">Enviar
                    <i class="material-icons right">send</i>
                </button>
            </div>
        </form>
    </div>
    <!--Import jQuery before materialize.js-->
    <script type="text/javascript" src="<?php echo PUBLIC_PATH ?>js/jquery-3.2.1.min.js"></script>
    <script type="text/javascript" src="<?php echo PUBLIC_PATH ?>js/materialize.min.js"></script>
    <script type="text/javascript" src="<?php echo PUBLIC_PATH ?>js/init.js"></script>
    <script>
//        window.open("<?php echo $urlacta ?>");
        $("#boton1").click(function () {
            $.ajax({
                data: {

                },
                url: "<?php echo PUBLIC_PATH ?>ciudadano/reportarerror/crear_reclamo",
                type: 'post',
                success: function (response) {

                    $("#mensajes_flash").html(response);
                }
            }
            );
        });
    </script>
</body>
</html>