<!DOCTYPE html>
<html>
    <head>
        <!--Import Google Icon Font-->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link type="text/css" rel="stylesheet" href="<?php echo PUBLIC_PATH ?>css/materialize.min.css"  media="screen,projection"/>
        <link type="text/css" rel="stylesheet" href="<?php echo PUBLIC_PATH ?>css/listado.css"  media="screen,projection"/>
        <link rel="stylesheet" href="<?php echo PUBLIC_PATH ?>css/alerta.css">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>
    <?php View::content() ?>
    <title>Actas digitales</title>
    <body>

        <!-- Header con titulo -->
        <nav>
            <div class="nav-wrapper">
                <a href="#" class="brand-logo center">Reportar error </a>
            </div>
        </nav>  
        <div class="row">
            <ul class="left-align col s6">
                <li><?php echo Html::img('home.png', 'Menu', array("width" => "48px", "height" => "48px")) ?></li>
                <li><?php echo Html::link("ciudadano/", "Menu"); ?></li>
            </ul>
            <ul class="right-align col s6">
                <li><?php echo Html::img('salida.jpg', 'Menu', array("width" => "48px", "height" => "48px")) ?></li>
                <li><?php echo Html::link('admin/index/logout', 'Salir') ?></li>
            </ul>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <table class="table table-bordered table-responsive" id="myTable">
                    <thead>
                        <tr>

                            <th>Tipo de reclamo</th>
                            <th>Descripción</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($listTiporeclamo as $tr) { ?>
                            <tr>
                                <td><?php echo $tr->nombretiporeclamo ?></td>
                                <td><?php echo $tr->descripciontiporeclamo ?></td>
                                <td><a href="<?php echo PUBLIC_PATH . "ciudadano/reportarerror/reclamar/" . $tr->id ?>"><img alt="" src="<?php echo PUBLIC_PATH ?>img/next.png"></a></td>
                            </tr>
                        <?php } ?>
                    </tbody>
                </table>
            </div>
        </div>

        <!--Import jQuery before materialize.js-->
        <script type="text/javascript" src="<?php echo PUBLIC_PATH ?>js/jquery-3.2.1.min.js"></script>
        <script type="text/javascript" src="<?php echo PUBLIC_PATH ?>js/materialize.min.js"></script>
        <script type="text/javascript" src="<?php echo PUBLIC_PATH ?>js/init.js"></script>
    </body>
</html>