<!DOCTYPE html>
<html>
    <head>
        <!-- Bootstrap -->
        <link href="<?php echo PUBLIC_PATH ?>gentelella/css/bootstrap.min.css" rel="stylesheet">
        <!-- Font Awesome -->
        <link href="<?php echo PUBLIC_PATH ?>gentelella/css/font-awesome.min.css" rel="stylesheet">
        <!-- NProgress -->
        <link href="<?php echo PUBLIC_PATH ?>gentelella/css/nprogress.css" rel="stylesheet">
        <!-- Custom Theme Style -->
        <link href="<?php echo PUBLIC_PATH ?>gentelella/css/custom.min.css" rel="stylesheet">
        <!-- jQuery -->
        <script src="<?php echo PUBLIC_PATH ?>gentelella/css/jquery.min.js"></script>
        <!-- Bootstrap -->
        <script src="<?php echo PUBLIC_PATH ?>gentelella/css/bootstrap.min.js"></script>
        <!--Import Google Icon Font-->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link type="text/css" rel="stylesheet" href="<?php echo PUBLIC_PATH ?>css/materialize.min.css"  media="screen,projection"/>
        <link type="text/css" rel="stylesheet" href="<?php echo PUBLIC_PATH ?>css/listado.css"  media="screen,projection"/>
        <link rel="stylesheet" href="<?php echo PUBLIC_PATH ?>css/registro.css">
        <link rel="stylesheet" href="<?php echo PUBLIC_PATH ?>css/baseFonts.css">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>

    <title>Reportar Error</title>
    <body>

        <!-- Header con titulo -->
        <nav class="nav-extended">
            <div class="nav-wrapper">
                <div class="nav-container">
                    <a href="#" class="brand-logo__link"><?php echo Html::img('logo.png', 'Menu', array("width" => "48px", "height" => "48px")) ?></a>
                    <?php echo Html::link("ciudadano/", "<div class=\"header-logo\">GESTIÓN DE ACTAS DIGITALES</div>"); ?>
                    <div class="nav-submenu">
                        > Actas digitales > Reportar Error
                    </div>
                </div>
                <div class="user-container">
                    <i style="margin-right: 5px" class="large material-icons white-text">account_circle</i>
                    <?php echo Auth::get('nombres') ?>
                    <div style="margin-left: 5px; padding-right: 5px"> | 
                        <?php echo Html::link('admin/index/logout', 'Cerrar sesión') ?>
                    </div>
                </div>
            </div>
        </nav>

        <div class="center row">
            <?php echo Form::open('ciudadano/reportarerror/crear_reclamo', 'post') ?>
            <div class="row ">
                <label><span style="font-size: 18px; margin-top: 15px; display: flex;" class="white-text">Selecciona el tipo de error y completá los datos</span></label>
                <div class="input-field">
                    <?php echo Form::dbselect('tiporeclamo.idtiporeclamo', 'nombretiporeclamo', array('tiporeclamo', 'find')) ?>
                </div>
            </div>
            <div class="row">
                <div class="input-field">
                    <?php echo Form::text('tiporeclamo.numeroacta') ?>
                    <label for="nroacta">Número acta</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field">
                    <?php echo Form::text('tiporeclamo.numerolibro') ?>
                    <label for="nrolibro">Número libro</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field">
                    <?php echo Form::text('tiporeclamo.nombrepropietarioacta') ?>
                    <label for="nombre">Nombre titular</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field">
                    <?php echo Form::text('tiporeclamo.apellidopropietarioacta') ?>
                    <label for="apellido">Apellido titular</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field">
                    <?php echo Form::textarea('tiporeclamo.observaciones', 'rows="10" cols="40"') ?>
                    <label for="comentarios">Escribe aquí tus comentarios</label>
                </div>
            </div>
            <?php View::content() ?>
            <div class="center withTopPad">
                <button class="btn-large waves-effect waves-light btn blue darken-3" type="submit" value="Verificar" id="boton1">Enviar
                    <i class="material-icons right">send</i>
                </button>
            </div>
        </form>
    </div>
    <!--Import jQuery before materialize.js-->
    <script type="text/javascript" src="<?php echo PUBLIC_PATH ?>js/jquery-3.2.1.min.js"></script>
    <script type="text/javascript" src="<?php echo PUBLIC_PATH ?>js/materialize.min.js"></script>
    <script type="text/javascript" src="<?php echo PUBLIC_PATH ?>js/init.js"></script>
    <script>
        $("#boton1").click(function () {
            $.ajax({
                data: {

                },
                url: "<?php echo PUBLIC_PATH ?>ciudadano/reportarerror/crear_reclamo",
                type: 'post',
                success: function (response) {

                    $("#mensajes_flash").html(response);
                }
            }
            );
        });
    </script>
</body>
</html>