<!DOCTYPE html>
<html >
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Multi Step Form with Progress Bar using jQuery and CSS3</title>
  
  <!--Import materialize.css-->
  <link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen,projection"/>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">
  <link rel="stylesheet" href="css/style.css">
  
</head>

<body>
  <!-- multistep form -->
<form id="msform">
  <!-- progressbar -->
  <ul id="progressbar">
    <li class="active">Account Setup</li>
    <li>Social Profiles</li>
    <li>Personal Details</li>
  </ul> 
  <!-- fieldsets 1: Elegir tipo de acta y parentezco -->
  <fieldset>
    <h2 class="fs-title">CREAR SOLICITUD</h2>
    <h3 class="fs-subtitle-left">Seleccione tipo de acta a solicitar</h3>
    <select>
        <option value="" disabled selected>Seleccion tipo de acta</option>
        <option value="1">Matrimonio</option>
        <option value="2">Nacimiento</option>
    </select>
    <h3 class="fs-subtitle-left">Seleccione parentesco del acta a solicitar</h3> 
     <p>
      <input class="with-gap" name="group3" type="radio" id="propia_radio"/>
      <label for="propia_radio">Propia</label>
    </p>
    <p>
      <input class="with-gap" name="group3" type="radio" id="hermano_radio"  />
      <label for="hermano_radio">Hermano</label>
    </p>
    <input type="button" name="next" class="next action-button" value="Next" />
  </fieldset>

  <!-- fieldsets 2: Se muestra una vista previa del acta cuando se selecciona -->
  <fieldset>
    <h2 class="fs-title">Elegir acta</h2>
    <h3 class="fs-subtitle">Estas son las opciones que puede seleccionar en base a sus elecciones</h3>
    

    <input type="button" name="previous" class="previous action-button" value="Previous" />
    <input type="button" name="reportar error" class="action-button" value="Reportar error" />
    <input type="button" name="next" class="next action-button" value="Next" />
  </fieldset>
  <fieldset>
    <h2 class="fs-title">Personal Details</h2>
    <h3 class="fs-subtitle">We will never sell it</h3>
    <input type="text" name="fname" placeholder="First Name" />
    <input type="text" name="lname" placeholder="Last Name" />
    <input type="text" name="phone" placeholder="Phone" />
    <textarea name="address" placeholder="Address"></textarea>
    <input type="button" name="previous" class="previous action-button" value="Previous" />
    <input type="submit" name="submit" class="submit action-button" value="Submit" />
  </fieldset>
</form>
  <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
  <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js'></script>
  <!--Import jQuery before materialize.js-->
  <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
  <script type="text/javascript" src="js/materialize.min.js"></script>
  
  <script src="js/register.js"></script>
  <script src="js/init.js"></script>

</body>
</html>
