<!DOCTYPE html>
<html >
    <head>
        <!-- Bootstrap -->
        <link href="<?php echo PUBLIC_PATH ?>gentelella/css/bootstrap.min.css" rel="stylesheet">
        <!-- Font Awesome -->
        <link href="<?php echo PUBLIC_PATH ?>gentelella/css/font-awesome.min.css" rel="stylesheet">
        <!-- NProgress -->
        <link href="<?php echo PUBLIC_PATH ?>gentelella/css/nprogress.css" rel="stylesheet">
        <!-- Custom Theme Style -->
        <link href="<?php echo PUBLIC_PATH ?>gentelella/css/custom.min.css" rel="stylesheet">
        <!-- jQuery -->
        <script src="<?php echo PUBLIC_PATH ?>gentelella/css/jquery.min.js"></script>
        <!-- Bootstrap -->
        <script src="<?php echo PUBLIC_PATH ?>gentelella/css/bootstrap.min.js"></script>
        <!-- Datatables -->
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/jquery.dataTables.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/dataTables.bootstrap.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/dataTables.buttons.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/buttons.bootstrap.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/buttons.flash.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/buttons.html5.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/buttons.print.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/jquery.maskedinput.js"></script>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <title>Crear Solicitud</title>

        <!--Import materialize.css-->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="stylesheet" href="<?php echo PUBLIC_PATH ?>css/style.css">
        <link rel="stylesheet" href="<?php echo PUBLIC_PATH ?>css/solicitud.css">
        <link rel="stylesheet" href="<?php echo PUBLIC_PATH ?>css/solicitud.min.css">
        <link rel="stylesheet" href="<?php echo PUBLIC_PATH ?>css/jquery-ui-1.10.3.custom.min.css" class="ace-main-stylesheet" id="main-ace-style" />
        <link rel="stylesheet" href="<?php echo PUBLIC_PATH ?>css/zoom.css">
        <link rel="stylesheet" type="text/css" href="<?php echo PUBLIC_PATH ?>css/registro.css">
        <link type="text/css" rel="stylesheet" href="<?php echo PUBLIC_PATH ?>css/materialize.min.css"  media="screen,projection"/>
    </head>

    <body>
        <!-- Header con titulo -->
        <nav>
            <div class="nav-wrapper">
                <a href="#" class="brand-logo center">Realizar solicitud</a>
            </div>
        </nav> 

        <div class="row">
            <ul class="left-align col s6">
                <li><?php echo Html::img('home.png', 'Menu', array("width" => "48px", "height" => "48px")) ?></li>
                <li><?php echo Html::link("ciudadano/", "Menu"); ?></li>
            </ul>
            <ul class="right-align col s6">
                <li><?php echo Html::img('salida.jpg', 'Menu', array("width" => "48px", "height" => "48px")) ?></li>
                <li><?php echo Html::link('admin/index/logout', 'Salir') ?></li>
            </ul>
        </div>

        <div id="mensajes_flash" >        
            <?php View::content() ?>
        </div>
        <!-- multistep form -->
        <form id="msform">
            <!-- progressbar -->
            <ul id="progressbar">
                <li class="active">Crear solicitud</li>
                <li>Verificar datos</li>
                <li>Pagar</li>
            </ul> 

            <ul class="left-align dropdown-menu">
            </ul>
            <!-- fieldsets 1: Elegir tipo de acta y parentezco -->
            <fieldset>
                <div id="respuesta" ></div>
                <h2 class="fs-title">CREAR SOLICITUD</h2>
                <h3 class="fs-subtitle-left">Seleccione tipo de acta a solicitar</h3>
                <div class="input-field" id="tipolibro">
                    <?php echo Form::dbselect('tipolibro.id', 'nombrelibro', array('tipolibro', 'find')) ?>                    
                </div>
                <h3
                    class="fs-subtitle-left">Seleccione parentesco del acta a solicitar</h3> 
                <div class="input-field" id="parentescos">

                </div>
                <input type="button" name="next" class="next action-button" value="Siguiente" id="boton1" />
            </fieldset>

            <!-- fieldsets 2: Se muestra una vista previa del acta cuando se selecciona -->
            <fieldset>
                <h2 class="fs-title">Acta a expedir</h2>
                <div id="img_container"><img id="img_acta" height="400" width="300" class="zoom"></div>
                <div class="col-sm-12">
                    <table class="table table-bordered table-responsive" id="myTable">
                        <thead>
                            <tr>
                                <th>Nombre</th>
                                <th>Apellido</th>
                                <th>DNI</th>
                                <th>Acta</th>
                                <th>Libro</th>
                                <th>Fecha nacimiento</th>
                            </tr>
                        </thead>
                        <tbody>

                        </tbody>
                    </table>
                </div>
                <input type="button" name="previous" class="previous action-button" value="Anterior" />
                <a href="<?php echo PUBLIC_PATH ?>ciudadano/reportarerror" class=" action-button" value="Reportar error" id="botonerror">Reportar error</a>
     <!--            <a href="<?php echo PUBLIC_PATH ?>ciudadano/solicitud/crear_solicitud" class=" action-button" value="Reportar error" id="botonerror">Confirmar</a> -->
                <input type="button" name="next" class="next action-button" value="Confirmar" id="boton2"/>
                <script>
                    $(document).ready(function () {
                        $('.zoom').hover(function () {
                            $(this).addClass('transition');
                        }, function () {
                            $(this).removeClass('transition');
                        });
                    });
                </script>
            </fieldset>
            <fieldset>
                <h2 class="fs-title">Formas de Pago</h2>
                <h3 class="fs-subtitle">Por el momento, utilizamos mercado pago para realizar los pagos</h3>
                <div class="row">
                    <a id="boton3" mp-mode="modal" href="https://www.mercadopago.com/mla/checkout/start?pref_id=279404435-82392bf5-6d97-4f7d-a621-1471c1627bf2" name="MP-payButton" class='blue-ar-l-rn-none' onreturn="execute_my_onreturn">Pagar</a>

                    <script type="text/javascript">
                        (function () {
                            function $MPC_load() {
                                window.$MPC_loaded !== true && (function () {
                                    var s = document.createElement("script");
                                    s.type = "text/javascript";
                                    s.async = true;
                                    s.src = document.location.protocol + "//secure.mlstatic.com/mptools/render.js";
                                    var x = document.getElementsByTagName('script')[0];
                                    x.parentNode.insertBefore(s, x);
                                    window.$MPC_loaded = true;
                                })();
                            }
                            window.$MPC_loaded !== true ? (window.attachEvent ? window.attachEvent('onload', $MPC_load) : window.addEventListener('load', $MPC_load, false)) : null;
                        })();
                    </script>
                </div>
            </fieldset>
        </form>
        <script src="<?php echo PUBLIC_PATH ?>js/jquery/jquery.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>js/jquery-ui-1.10.3.js"></script>
        <!--<script type="text/javascript" src="<?php // echo PUBLIC_PATH                        ?>js/jquery-3.2.1.min.js"></script>-->
        <script src="<?php echo PUBLIC_PATH ?>js/jquery.easing.min.js"></script>
        <!--Import jQuery before materialize.js-->
        <script type="text/javascript" src="<?php echo PUBLIC_PATH ?>js/materialize.min.js"></script>
        <!--<script src="<?php echo PUBLIC_PATH ?>js/registro.js"></script>-->
        <script src="<?php echo PUBLIC_PATH ?>js/init.js"></script>
        <!-- FastClick -->
        <script src="<?php echo PUBLIC_PATH ?>gentelella/css/fastclick.js"></script>
        <!-- NProgress -->
        <script src="<?php echo PUBLIC_PATH ?>gentelella/css/nprogress.js"></script>
        <!-- Custom Theme Scripts -->

        <script src="<?php echo PUBLIC_PATH ?>js/jquery/jquery.kumbiaphp.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>gentelella/css/custom.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>js/solicitarActa.js"></script>
        <script src="https://secure.mlstatic.com/sdk/javascript/v1/mercadopago.js"></script>


        <script>
                        $("#tipolibro_id").change(function () {
                            if (($("#tipolibro_id option:selected").val() != "")) {

                                $.ajax({
                                    data: {
                                        'tipolibro': $("#tipolibro_id option:selected").val()
                                    },
                                    url: "<?php echo PUBLIC_PATH ?>ciudadano/index/buscar_parentesco_tipolibro",
                                    type: 'post',
                                    dataType: "json",
                                    success: function (response) {
                                        html = "";
                                        $.each(response, function (i, row) {
                                            html += '<p>'
                                            html += '<input class="with-gap" name="group3" value="' + row.id + '" type="radio" id="' + row.nombreparentesco + '_radio">'
                                            html += '<label for="' + row.nombreparentesco + '_radio">' + row.nombreparentesco + '</label>'
                                            html += '</p>'
                                        })
                                        $("#parentescos").html(html);
                                    }
                                });
                            }
                        });
                        $("#boton1").click(function () {
                            if (($("#tipolibro_id option:selected").val() != "")) {

                                $.ajax({
                                    data: {
                                        'tipolibro': $("#tipolibro_id option:selected").val(),
                                        'parentesco': $('input[name=group3]:checked').val()
                                    },
                                    url: "<?php echo PUBLIC_PATH ?>ciudadano/index/buscar_imagen",
                                    type: 'post',
                                    dataType: "json",
                                    success: function (response) {
                                        imagen = response[0]
                                        $("#img_acta").attr("src", imagen.imagen);
                                        if (imagen.persona == null) {
                                            $('#boton2').attr("disabled", "disabled")
                                            $("#myTable").hide()
                                        } else {
                                            $('#boton2').removeAttr("disabled")
                                            $("#myTable").show()
                                            html = "";
                                            html += '<tr>'
                                            html += '<td>' + imagen.persona + '</td>'
                                            html += '<td>' + imagen.apellido + '</td>'
                                            html += '<td>' + imagen.dni + '</td>'
                                            html += '<td>' + imagen.nroacta + '</td>'
                                            html += '<td>' + imagen.nrolibro + '</td>'
                                            html += '<td>' + imagen.fecha_nacimiento + '</td>'
                                            html += '</tr>'
                                            $("#myTable tbody").html(html);
                                        }
                                    },
                                    fail: function (response) {
                                        $("#respuesta").html("No existe la imagen del acta")
                                    }
                                });
                            }
                        });
                        $("#botonerror").click(function () {
                            if (($("#tipolibro_id option:selected").val() != "")) {

                                $.ajax({
                                    data: {
//                                        'tipolibro': $("#tipolibro_id option:selected").val(),
//                                        'parentesco': $('input[name=group3]:checked').val()
                                    },
                                    url: "<?php echo PUBLIC_PATH ?>olvido/index",
                                    type: 'post',
                                    dataType: "json",
//                                    success: function (response) {
//                                        imagen = response[0]
//                                        $("#img_acta").attr("src", imagen.imagen);
//                                    },
//                                    fail: function (response) {
//                                        $("#respuesta").html("No existe la imagen del acta")
//                                    }
                                });
                            }
                        });
                        $("#boton2").click(function () {
                            $.ajax({
                                data: {

                                },
                                url: "<?php echo PUBLIC_PATH ?>ciudadano/solicitud/crear_solicitud",
                                type: 'post',
                                success: function (response) {

                                    $("#mensajes_flash").html(response);
                                }
                            }
                            );
                        });
                        function execute_my_onreturn(json) {
                            //alert(json.collection_id) //tengo el numero de comprobante
                            if (json.collection_status == 'approved') {
                                alert('Pago acreditado');
//                                $('#boton3').html("Finalizado")
//                                $('#boton3').removeAttr("name")
//                                $('#boton3').attr("href", "<?php echo PUBLIC_PATH ?>ciudadano")
                                window.open("<?php echo PUBLIC_PATH ?>ciudadano");
                            } else if (json.collection_status == 'pending') {
                                alert('El usuario no completó el pago');
                            } else if (json.collection_status == 'in_process') {
                                alert('El pago está siendo revisado');
                            } else if (json.collection_status == 'rejected') {
                                alert('El pago fué rechazado, el usuario puede intentar nuevamente el pago');
                            } else if (json.collection_status == null) {
                                alert('El usuario no completó el proceso de pago, no se ha generado ningún pago');
                            }
                            $.ajax({
                                url: "<?php echo PUBLIC_PATH ?>ciudadano/index/generar_pdf_firmar_mail",
                                type: 'post',
                                data: {
                                    'estado': json.collection_status,
                                    'nrocupon': json.collection_id
                                },
                                success: function (response) {
                                    $('#boton3').html("Finalizado")
                                    $('#boton3').removeAttr("name")
                                    $('#boton3').attr("href", "<?php echo PUBLIC_PATH ?>ciudadano")
                                }
                            });
                        }
        </script>
    </body>
</html>
