<!DOCTYPE html>
<html >
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <title>Crear Solicitud</title>

        <!--Import materialize.css-->
        <link type="text/css" rel="stylesheet" href="<?php echo PUBLIC_PATH ?>css/materialize.min.css"  media="screen,projection"/>
        <link rel="stylesheet" href="<?php echo PUBLIC_PATH ?>css/style.css">
        <link rel="stylesheet" href="<?php echo PUBLIC_PATH ?>css/solicitud.css">
        <link rel="stylesheet" href="<?php echo PUBLIC_PATH ?>css/alerta.css">
        <link rel="stylesheet" href="<?php echo PUBLIC_PATH ?>css/solicitud.min.css">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    </head>

    <body>
        <?php view::content() ?>
        <!-- multistep form -->
        <form id="msform">
            <!-- progressbar -->
            <ul id="progressbar">
                <li class="active">Account Setup</li>
                <li>Social Profiles</li>
                <li>Personal Details</li>
            </ul> 
            <ul class="left-align dropdown-menu">
                <li><?php echo Html::img('home.png', 'Menu', array("width" => "48px", "height" => "48px")) ?></li>
                <li><?php echo Html::link("ciudadano/", "Menu"); ?></li>
                </ul>
            <ul class="right-align dropdown-menu">
                <li><?php echo Html::link('admin/index/logout', 'Salir') ?></li>
            </ul>
            
            <ul class="left-align dropdown-menu">
            </ul>
            <!-- fieldsets 1: Elegir tipo de acta y parentezco -->
            <fieldset>
                <div id="respuesta" ></div>
                <h2 class="fs-title">CREAR SOLICITUD</h2>
                <h3 class="fs-subtitle-left">Seleccione tipo de acta a solicitar</h3>
                <div class="input-field" id="tipolibro">
                    <?php echo Form::dbselect('tipolibro.id', 'nombrelibro', array('tipolibro', 'find')) ?>                    
                </div>
                <h3
                    class="fs-subtitle-left">Seleccione parentesco del acta a solicitar</h3> 
                <div class="input-field" id="parentescos">

                </div>
                <input type="button" name="next" class="next action-button" value="Siguiente" id="boton1" />
            </fieldset>

            <!-- fieldsets 2: Se muestra una vista previa del acta cuando se selecciona -->
            <fieldset>
                <h2 class="fs-title">Acta a expedir</h2>
                <img id="img_acta" height="400" width="300">
                <input type="button" name="previous" class="previous action-button" value="Anterior" />
                <input type="button" name="reportar error" class="action-button" value="Reportar error" />
                <input type="button" name="next" class="next action-button" value="Siguiente" id="boton2"/>
            </fieldset>
            <fieldset>
                <h2 class="fs-title">Formas de Pago</h2>
                <h3 class="fs-subtitle">Elija tipo de tarjeta</h3>
                <div class="row">
                    <div class="input-field">
                        <select>
                            <option value="" disabled selected>Elija tipo de tarjeta</option>
                            <option value="1">Visa Debito</option>
                            <option value="2">Visa Credito</option>
                        </select>
                    </div>
                </div>
                <input type="text" name="fname" placeholder="Numero de tarjeta" />
                <input type="text" name="lname" placeholder="Codigo de seguridad" />
                <input type="button" name="previous" class="previous action-button" value="Anterior" />
                <input type="submit" name="submit" class="submit action-button" value="Pagar" />
            </fieldset>
        </form>
        <script src="<?php echo PUBLIC_PATH ?>js/jquery/jquery.min.js"></script>
        <!--<script type="text/javascript" src="<?php // echo PUBLIC_PATH    ?>js/jquery-3.2.1.min.js"></script>-->
        <script src="<?php echo PUBLIC_PATH ?>js/jquery.easing.min.js"></script>
        <!--Import jQuery before materialize.js-->
        <script type="text/javascript" src="<?php echo PUBLIC_PATH ?>js/materialize.min.js"></script>
        <!--<script src="<?php echo PUBLIC_PATH ?>js/registro.js"></script>-->
        <script src="<?php echo PUBLIC_PATH ?>js/init.js"></script>
        <!-- FastClick -->
        <script src="<?php echo PUBLIC_PATH ?>gentelella/css/fastclick.js"></script>
        <!-- NProgress -->
        <script src="<?php echo PUBLIC_PATH ?>gentelella/css/nprogress.js"></script>
        <!-- Custom Theme Scripts -->

        <script src="<?php echo PUBLIC_PATH ?>js/jquery/jquery.kumbiaphp.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>gentelella/css/custom.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>js/solicitarActa.js"></script>
        <script>
            $("#tipolibro_id").change(function () {
                if (($("#tipolibro_id option:selected").val() != "")) {

                    $.ajax({
                        data: {
                            'tipolibro': $("#tipolibro_id option:selected").val()
                        },
                        url: "<?php echo PUBLIC_PATH ?>ciudadano/index/buscar_parentesco_tipolibro",
                        type: 'post',
                        dataType: "json",
                        success: function (response) {
                            html = "";
                            $.each(response, function (i, row) {
                                html += '<p>'
                                html += '<input class="with-gap" name="group3" value="' + row.id + '" type="radio" id="' + row.nombreparentesco + '_radio">'
                                html += '<label for="' + row.nombreparentesco + '_radio">' + row.nombreparentesco + '</label>'
                                html += '</p>'
                            })
                            $("#parentescos").html(html);
                        }
                    });
                }
            });
            $("#boton1").click(function () {
                if (($("#tipolibro_id option:selected").val() != "")) {

                    $.ajax({
                        data: {
                            'tipolibro': $("#tipolibro_id option:selected").val(),
                            'parentesco': $('input[name=group3]:checked').val()
                        },
                        url: "<?php echo PUBLIC_PATH ?>ciudadano/index/buscar_imagen",
                        type: 'post',
                        dataType: "json",
                        success: function (response) {
                            imagen = response[0]
                            $("#img_acta").attr("src", imagen.imagen);
                        },
                        fail: function (response) {
                            $("#respuesta").html("No existe la imagen del acta")
                        }
                    });
                }
            });
        </script>
    </body>
</html>
