<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <title>Terminos y condiciones</title>

        <!-- CSS  -->
        <link href="<?php echo PUBLIC_PATH ?>css/fuentes.css" type="text/css" rel="stylesheet">
        <link href="<?php echo PUBLIC_PATH ?>css/materialize.css" type="text/css" rel="stylesheet" media="screen,projection"/>
        <link href="<?php echo PUBLIC_PATH ?>css/style.css" type="text/css" rel="stylesheet" media="screen,projection"/>
    </head>
    <body>
        <nav class="nav-extended">
            <div class="nav-wrapper">
                <div href="#" class="brand-logo center"><a>Terminos y condiciones</a></div>
            </div>
        </nav>

        <div id="index-banner">
            <div class="section no-pad-bot">
                <div class="container">
                    <div class="row center" style="text-align: left">
                        <h6>Gestión Digital de Actas no se responsabilizará de ninguna manera por los actos ejecutados por los usuarios ya sea que los mismos se lleven a cabo en virtud de una relación entre usuarios posibilitada por el portal o no, como así tampoco por las consecuencias fructíferas, no fructíferas, culposas o dolosas que de estos actos surjan.
                            Respecto del manejo de la información de los usuarios, según lo dispone la legislación actual (Ley 24766 Protección de datos personales y 25326 Confidencialidad de la información), Gestión Digital de Actas no divulgará la información almacenada por los usuarios.

                            <br><br>
                            
                            Este contrato (el "Contrato") contiene los términos, condiciones y limitaciones que rigen para el uso del sitio y servicio denominado gestiondigital.gob.ar marca registrada y de propiedad de Documentalia SRL CUIT 30-70959253-6 en adelante “La Empresa”, y pone a disposición de la persona interesada en su utilización (el "Usuario") en el sitio www.gestiondigital.com (el "Sitio").

                            <br><br>
                            <br><br>
                          
                            <b>1. Aceptación del contrato y sus modificaciones</b>
                            <br><br>
                            La Empresa podrá modificar unilateralmente el Contrato. Las modificaciones serán obligatorias desde su publicación en el Sitio o desde su notificación al Usuario, lo que suceda primero, sin perjuicio de la facultad del Usuario de terminar el Contrato. 
                            El sistema
                            Gestión Digital de Actas almacenará los datos suministrados en sus bases de datos siendo accesible sólo para los fines del sistema, salvo los casos excepcionales dispuestos en la ley 25326 de confidencialidad de la información. 
                            Se mantendrá al resguardo de terceros la información suministrada por el Usuario, en servidores con las medidas de seguridad necesarias. 
                            Gestión Digital de Actas se reserva el derecho de determinar por cuánto tiempo conservará los datos de usuarios, pudiendo eliminarlos cuando sea necesario o conveniente.
                            Se considera fecha y hora de inicio de gestiones a partir del momento en que el usuario  confirma los datos aportados para las gestiones. 
                            Gestión Digital de Actas se reservará el derecho de modificar unilateralmente, en cualquier momento y sin aviso previo, la presentación y configuración del portal, así como las condiciones de prestación de los Servicios.
        
                            <br><br>
                            <br><br>

                            <b>2. Costos del Servicio</b>
                            <br><br>
                            Gestión Digital de Actas cobra los códigos provinciales nº 221 y 224 en concepto de servicios de gestoría. 
                            Exclusión de responsabilidad de "Gestión Digital de Actas"
                            Se realizarán todos los esfuerzos lógicos necesarios para la obtención de cada partida y para el cumplimiento de los "Plazos de Gestión Promedios Estimados" en el caso de que las partidas no estén digitalizadas. 
                            El Usuario queda notificado y asumirá el riesgo sobre los plazos de gestión en el caso de la digitalización de un acta y los posibles contratiempos que pudieran existir para la obtención de las partidas. 
                            Se harán todos los esfuerzos razonables para asegurar que los plazos estimados de gestión, procesamiento y operaciones con terceras empresas, como las entidades recaudadoras sean efectuadas de acuerdo a los plazos de gestión de referencia y tiempos de entrega estimados, sin embargo, algunos factores, pueden determinar retrasos en el tiempo necesario para culminar un proceso necesario para llevar adelante un servicio. El Usuario entiende que estas fallas son ajenas a la Gestión Digital de Actas y la exime de toda responsabilidad por los inconvenientes o perjuicios derivados de estas fallas.
                            Uso del sitio
                            El Usuario se compromete a no utilizar el Sistema para obtener documentos que deriven en operaciones ilegales, incluyendo pero no limitado a cualquier producto o servicio que infrinja leyes de propiedad intelectual o derechos de terceros. El Usuario no utilizará los servicios para ningún tipo de actividad que pueda ser considerada fraudulenta o ilegal y que devenguen perjuicios para El Estado o terceros como consecuencia del uso indebido del sitio de su propiedad y de la documentación obtenida mediante los servicios prestados, y declara que el mismo es solicitado bajo interés legítimo con el sólo hecho de contratar el servicio.  
                            Cesión
                            El Usuario no puede ceder el Contrato, y cualquier intento de cesión por su parte será considerado nulo y de ningún efecto. 
                            Gestión Digital de Actas tiene amplias facultades para ceder o transferir el Contrato o cualquier derecho que tenga bajo el mismo sin necesidad de notificación o consentimiento por parte del Usuario.
                            Información introducida por el usuario en el sitio
                            El Usuario se obliga a no introducir en el Sitio información de carácter obsceno, ofensivo o agraviante, o que contenga amenazas, virus u otros programas perjudiciales o mecanismos para captar o distorsionar información contenida en el Sitio.

                            <br><br>
                            <br><br>
                             
                            <b>3. Derechos sobre el sitio y su contenido</b>
                            <br><br>
                            El Sitio, las marcas y los logotipos y todo otro contenido del Sitio son propiedad de Gestión Digital de Actas y están protegidos por las normas de derechos de autor, marcas, propiedad intelectual, inventos, software y demás normas aplicables y está prohibida su copia, reproducción, venta o cualquier otro uso comercial o difusión no autorizado.
                            Toda la información brindada por el Usuario al Sitio se entiende hecha en carácter de declaración jurada. 
                            Información del usuario
                            El Usuario autoriza a utilizar su información personal para fines propios de operaciones de gestión y procesos necesarios para llevar adelante un servicio. Gestión Digital de Actas no publicará, venderá ni cederá a terceros la información recabada del Usuario, salvo que deba ser revelada en cumplimiento de una orden judicial o de autoridad administrativa.  
                            Jurisdicción y ley aplicable
                            Se pacta la jurisdicción de los tribunales ordinarios de la Ciudad de Mendoza y la aplicación de la ley argentina con exclusión de toda norma sobre conflictos de leyes. Se fija como domicilio de Gestión Digital de Actas Peltier 351 Piso 0, Oficina Dirección, CP 5500, Ciudad de Mendoza, República Argentina. </h6>
                    </div>
                    <br><br>
                </div>
            </div>
           
        </div>
        <!--  Scripts-->
        <script src="<?php echo PUBLIC_PATH ?>js/jquery-3.2.1.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>js/materialize.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>js/init.js"></script>

    </body>
</html>