<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <title>Terminos y condiciones</title>

        <!-- CSS  -->
        <link href="<?php echo PUBLIC_PATH ?>css/fuentes.css" type="text/css" rel="stylesheet">
        <link href="<?php echo PUBLIC_PATH ?>css/materialize.css" type="text/css" rel="stylesheet" media="screen,projection"/>
        <link href="<?php echo PUBLIC_PATH ?>css/style.css" type="text/css" rel="stylesheet" media="screen,projection"/>
    </head>
    <body>
        <nav class="nav-extended">
            <div class="nav-wrapper">
                <div href="#" class="brand-logo center"><a>Terminos y condiciones</a></div>
            </div>
        </nav>

        <div id="index-banner" class="parallax-container">
            <div class="section no-pad-bot">
                <div class="container">
                    <br><br>
                    <div class="row center">
                        <p>Gestión Digital de Actas no se responsabilizará de ninguna manera por los actos ejecutados por los usuarios ya sea que los mismos se lleven a cabo en virtud de una relación entre usuarios posibilitada por el portal o no, como así tampoco por las consecuencias fructíferas, no fructíferas, culposas o dolosas que de estos actos surjan.
                            Respecto del manejo de la información de los usuarios, según lo dispone la legislación actual (Ley 24766 Protección de datos personales y 25326 Confidencialidad de la información), Gestión Digital de Actas no divulgará la información almacenada por los usuarios.<br/>
                            Este contrato (el "Contrato") contiene los términos, condiciones y limitaciones que rigen para el uso del sitio y servicio denominado gestiondigital.gob.ar marca registrada y de propiedad de Documentalia SRL CUIT 30-70959253-6 en adelante “La Empresa”, y pone a disposición de la persona interesada en su utilización (el "Usuario") en el sitio www.gestiondigital.com (el "Sitio").</p>
                        1. Aceptación del contrato y sus modificaciones
                        La Empresa podrá modificar unilateralmente el Contrato. Las modificaciones serán obligatorias desde su publicación en el Sitio o desde su notificación al Usuario, lo que suceda primero, sin perjuicio de la facultad del Usuario de terminar el Contrato.
                        El sistema
                        Gestión Digital de Actas almacenará los datos suministrados en sus bases de datos siendo accesible sólo para los fines del sistema, salvo los casos excepcionales dispuestos en la ley 25326 de confidencialidad de la información. 
                            Se mantendrá al resguardo de terceros la información suministrada por el Usuario, en servidores con las medidas de seguridad necesarias. 
                            Gestión Digital de Actas se reserva el derecho de determinar por cuánto tiempo conservará los datos de usuarios, pudiendo eliminarlos cuando sea necesario o conveniente.
                            Se considera fecha y hora de inicio de gestiones a partir del momento en que el usuario  confirma los datos aportados para las gestiones. 
                            Gestión Digital de Actas se reservará el derecho de modificar unilateralmente, en cualquier momento y sin aviso previo, la presentación y configuración del portal, así como las condiciones de prestación de los Servicios.
                        Costos del Servicio
                        Gestión Digital de Actas cobra los códigos provinciales nº 221 y 224 en concepto de servicios de gestoría. 
                            Exclusión de responsabilidad de "Gestión Digital de Actas"
                        
                    </div>
                    <br><br>
                </div>
            </div>
            <div class="parallax cropper"><img src="<?php echo PUBLIC_PATH ?>img/background123.jpg" alt="Unsplashed background img 1"></div>
        </div>
        <!--  Scripts-->
        <script src="<?php echo PUBLIC_PATH ?>js/jquery-3.2.1.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>js/materialize.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>js/init.js"></script>

    </body>
</html>