<!DOCTYPE html>
<html>

    <head>
        <!-- Bootstrap -->
        <link href="<?php echo PUBLIC_PATH ?>gentelella/css/bootstrap.min.css" rel="stylesheet">
        <!-- Font Awesome -->
        <link href="<?php echo PUBLIC_PATH ?>gentelella/css/font-awesome.min.css" rel="stylesheet">
        <!-- NProgress -->
        <link href="<?php echo PUBLIC_PATH ?>gentelella/css/nprogress.css" rel="stylesheet">
        <!-- Custom Theme Style -->
        <link href="<?php echo PUBLIC_PATH ?>gentelella/css/custom.min.css" rel="stylesheet">
        <!-- jQuery -->
        <script src="<?php echo PUBLIC_PATH ?>gentelella/css/jquery.min.js"></script>
        <!-- Bootstrap -->
        <script src="<?php echo PUBLIC_PATH ?>gentelella/css/bootstrap.min.js"></script>
        <!-- Datatables -->
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/jquery.dataTables.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/dataTables.bootstrap.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/dataTables.buttons.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/buttons.bootstrap.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/buttons.flash.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/buttons.html5.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/buttons.print.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/jquery.maskedinput.js"></script>
        <link rel="stylesheet" type="text/css" href="<?php echo PUBLIC_PATH ?>css/alerta.css">
        <link rel="stylesheet" type="text/css" href="<?php echo PUBLIC_PATH ?>css/baseFonts.css">
        <link type="text/css" rel="stylesheet" href="<?php echo PUBLIC_PATH ?>css/materialize.min.css"  media="screen,projection"/>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

        <title>Verificar validez</title>

        <script src="<?php echo PUBLIC_PATH ?>js/prefixfree.min.js"></script>

    </head>
    <body>

        <!-- Header con titulo -->
        <nav>
            <div class="nav-wrapper">
                <a href="#" class="brand-logo center">Verificar Validez</a>
            </div>
        </nav> 

    <div class="center row withTopPad">
        
    <!-- Inicio seccion izquierda para validar acta -->
        <div class= "row">
            <div id="mensajes_flash"></div> 
            <label>Verificá la validez del acta ingresando el dni y el código de pago:</label>
            <input type="text" placeholder="DNI" name="dni" id = "textodni"><br>
            <input type="text" placeholder="Código" name="codigo" id="textocodigo"><br>
            <div>
                <a class="btn-large waves-effect waves-light btn" id="botonverificar">Verificar</a>
            </div>
        </div>
    </div>
        <!--Import jQuery before materialize.js-->
        <script type="text/javascript" src="<?php echo PUBLIC_PATH ?>js/jquery-3.2.1.min.js"></script>
        <script type="text/javascript" src="<?php echo PUBLIC_PATH ?>js/materialize.min.js"></script>
        <script type="text/javascript" src="<?php echo PUBLIC_PATH ?>js/jquery/jquery.kumbiaphp.js"></script>
        <!-- En init.js esta declarada la inicializacion de los selectores utilizados por materialize-->
        <script src="<?php echo PUBLIC_PATH ?>js/init.js"></script>
        <script>
        $("#botonverificar").click(function () {
            $.ajax({
                data: {
                    'codigo': $("#textocodigo").val(),
                    'dni': $("#textodni").val()
                },
                url: "<?php echo PUBLIC_PATH ?>verificarentidad/verificar_validez_entidad",
                type: 'post',
                success: function (response) {
                           
                            $("#mensajes_flash").html(response);
                        }
            }
            );
        });
    </script>
    </div>  
    </body>

</html>