<!DOCTYPE html>
<html>

    <head>
        <!-- Custom Theme Style -->
        <link href="<?php echo PUBLIC_PATH ?>gentelella/css/custom.min.css" rel="stylesheet">
        <!-- jQuery -->
        <script src="<?php echo PUBLIC_PATH ?>gentelella/css/jquery.min.js"></script>
        <link rel="stylesheet" type="text/css" href="<?php echo PUBLIC_PATH ?>css/baseFonts.css">
        <link type="text/css" rel="stylesheet" href="<?php echo PUBLIC_PATH ?>css/materialize.min.css"  media="screen,projection"/>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

        <title>Verificar validez</title>

        <script src="<?php echo PUBLIC_PATH ?>js/prefixfree.min.js"></script>

    </head>
    <body>

        <!-- Header con titulo -->
         <nav class="nav-extended">
            <div class="nav-wrapper">
                <div class="nav-container">
                    <a href="#" class="brand-logo__link"><?php echo Html::img('logo.png', 'Menu', array("width" => "48px", "height" => "48px")) ?></a>
                    <?php echo Html::link("/", "<div class=\"header-logo\">GESTIÓN DE ACTAS DIGITALES</div>"); ?>
                    <div class="nav-submenu">
                        > Verificar vigencia de acta
                    </div>
                </div>
            </div>
        </nav>
        <div class="center row withTopPad">
            <div class= "row">
                <?php echo Html::img('verificar.png', 'Verificar', array("width" => "200px", "height" => "200px")) ?><br>
                <label><span style="font-size: 18px; margin-top: 15px; display: flex;" class="white-text">Verificá la validez del acta ingresando el dni y el código de pago:</span></label>
                <input type="text" placeholder="DNI" name="dni" id = "textodni"><br>
                <input type="text" placeholder="Código" name="codigo" id="textocodigo"><br>
                <div>
                    <a class="btn-large waves-effect waves-light btn blue darken-3" id="botonverificar">Verificar</a>
                </div>
            </div>
        </div>
        <!--Import jQuery before materialize.js-->
        <script type="text/javascript" src="<?php echo PUBLIC_PATH ?>js/jquery-3.2.1.min.js"></script>
        <script type="text/javascript" src="<?php echo PUBLIC_PATH ?>js/materialize.min.js"></script>
        <script type="text/javascript" src="<?php echo PUBLIC_PATH ?>js/jquery/jquery.kumbiaphp.js"></script>
        <!-- En init.js esta declarada la inicializacion de los selectores utilizados por materialize-->
        <script src="<?php echo PUBLIC_PATH ?>js/init.js"></script>
        <script>
            $("#botonverificar").click(function () {
                $.ajax({
                    data: {
                        'codigo': $("#textocodigo").val(),
                        'dni': $("#textodni").val()
                    },
                    url: "<?php echo PUBLIC_PATH ?>verificarentidad/verificar_validez_entidad",
                    type: 'post',
                    success: function (response) {
                        Materialize.toast(response.split('</button>')[1].split('</div>')[0], 4000);
                    }
                }
                );
            });
        </script>
    </div>  
</body>

</html>