<!DOCTYPE html>
<html>
    <head>
        <!-- Bootstrap -->
        <link href="<?php echo PUBLIC_PATH ?>gentelella/css/bootstrap.min.css" rel="stylesheet">
        <!-- Font Awesome -->
        <link href="<?php echo PUBLIC_PATH ?>gentelella/css/font-awesome.min.css" rel="stylesheet">
        <!-- NProgress -->
        <link href="<?php echo PUBLIC_PATH ?>gentelella/css/nprogress.css" rel="stylesheet">
        <!-- Custom Theme Style -->
        <link href="<?php echo PUBLIC_PATH ?>gentelella/css/custom.min.css" rel="stylesheet">
        <!-- jQuery -->
        <script src="<?php echo PUBLIC_PATH ?>gentelella/css/jquery.min.js"></script>
        <!-- Bootstrap -->
        <script src="<?php echo PUBLIC_PATH ?>gentelella/css/bootstrap.min.js"></script>
        <!-- Datatables -->
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/jquery.dataTables.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/dataTables.bootstrap.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/dataTables.buttons.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/buttons.bootstrap.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/buttons.flash.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/buttons.html5.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/buttons.print.min.js"></script>
        <script src="<?php echo PUBLIC_PATH ?>gentelella/javascript/jquery/jquery.maskedinput.js"></script>
        <!--Import materialize.css-->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="stylesheet" href="<?php echo PUBLIC_PATH ?>css/style.css">
        <link rel="stylesheet" href="<?php echo PUBLIC_PATH ?>css/solicitud.css">
        <link rel="stylesheet" href="<?php echo PUBLIC_PATH ?>css/solicitud.min.css">
        <link rel="stylesheet" type="text/css" href="<?php echo PUBLIC_PATH ?>css/registro.css">
        <link rel="stylesheet" type="text/css" href="<?php echo PUBLIC_PATH ?>css/alerta.css">
        <link type="text/css" rel="stylesheet" href="<?php echo PUBLIC_PATH ?>css/materialize.min.css"  media="screen,projection"/>
        <script src="<?php echo PUBLIC_PATH ?>js/jquery/jquery.min.js"></script>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <title>Verificar validez</title>
    </head>
    <body>
        <!-- Header con titulo -->
        <nav>
            <div class="nav-wrapper">
                <a href="#" class="brand-logo center">Verificar validez</a>
            </div>
        </nav>  
        <div class="row">
            <ul class="left-align col s6">
                <li><?php echo Html::img('home.png', 'Menu', array("width" => "48px", "height" => "48px")) ?></li>
                <li><?php echo Html::link("ciudadano/", "Menu"); ?></li>
            </ul>
            <ul class="right-align col s6">
                <li><?php echo Html::img('salida.jpg', 'Menu', array("width" => "48px", "height" => "48px")) ?></li>
                <li><?php echo Html::link('admin/index/logout', 'Salir') ?></li>
            </ul>
        </div>
        <div class="login">
            <div id="mensajes_flash" >        
                <?php View::content() ?>
                <div>
                    <ul class="center col s12">Verificá la validez del acta ingresando el dni y el código de pago: </ul>
                    <ul class="center col s12"><?php echo Html::img('verificar.jpeg', 'Verificar', array("width" => "200px", "height" => "200px")) ?></ul></li>
                </div>
                <div class="center">
                    <div class="input-field">
                        <input type="text" placeholder="Código" name="codigo" id="input1"><br>
                        <input class="btn-large waves-effect waves-light btn" type="submit" value="Verificar" id="boton1">
                    </div>
                </div>
            </div> 
        </div>
        <script>
            $("#boton1").click(function () {
                $.ajax({
                    data: {
                        'codigo': $("#input1").val()
                    },
                    url: "<?php echo PUBLIC_PATH ?>ciudadano/verificar/verificar_validez_usuario",
                    type: 'post',
                    success: function (response) {

                        $("#mensajes_flash").html(response);
                    }
                }
                );
            });
        </script>
    </body>
</html>