<div class="content">
    <?php View::content(); ?>
    <h3>Crear Departamento<h3>
            <?php echo Form::open(); // por defecto llama a la misma url ?>
            <label>Nombre Departamento
                <?php echo Form::text('departamento.nombredepartamento') ?></label>
            <?php echo Form::dbselect('departamento.idprovincia', 'nombreprovincia', array('provincia','find')) ?>
            <?php echo Form::submit('Agregar') ?>
            <?php echo Form::close() ?>
            </div>