<div class="content">
    <?php View::content(); ?>
    <h3>Editar Departamento<h3>

            <?php echo Form::open(); // por defecto llama a la misma url ?>
            <label>Nombre departamento
                <?php echo Form::text('departamento.nombredepartamento') ?></label>
            <?php echo Form::hidden('departamento.id') ?>
            <label>Seleccione Provincia
            <?php echo Form::dbselect('departamento.idprovincia', 'nombreprovincia', array('provincia','find')) ?>
            <?php echo Form::submit('Actualizar') ?>
            <?php echo Form::close() ?>
            </div>