<div class="content">
    <?php View::content(); ?>
    <h3>Departamento</h3>
    <ul>
    <?php foreach ($listDepartamento->items as $item) : ?>
    <li>
        <?php echo Html::linkAction("edit/$item->id/", 'Editar') ?>
        <?php echo Html::linkAction("del/$item->id/", 'Borrar') ?>
        <strong><?php echo $item->nombredepartamento ?></strong>
    </li>
    <?php endforeach; ?>
    </ul>
 
     <!-- ejemplo manual de paginador, hay partial listos en formato digg, clasic,.... -->
    <?php if($listDepartamento->prev) echo Html::linkAction("index/$listDepartamento->prev/", '<< Anterior |'); ?>
    <?php if($listDepartamento->next) echo Html::linkAction("index/$listDepartamento->next/", 'Próximo >>'); ?>
</div>