<span>Se ha encontrado <strong><?php echo count($lista1) ?> registros</strong></span>
<div class="row">
    <div class="col-sm-12">
        <table class="table table-bordered table-responsive" id="myTable">
            <thead>
                <tr bgcolor="#AABFD7" align="center">
                    <th>N° de solicitud</th>
                    <th>Nombre propietario acta</th>
                    <th>Parentesco</th>
                    <th>Cupon de pago</th>
                    <th>Fecha de pago</th>
                    <th>Estado solicitud </th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($lista1 as $af) { ?>
                    <tr>
                        <td><?php echo $af->id ?></td>
                        <td><?php echo $af->nombrepropietarioacta ?></td>
                        <td><?php echo $af->nombreparentesco ?></td>
                        <td><?php echo $af->codigodepago ?></td>
                        <td><?php echo $af->fechacambioestado ?></td>
                        <td><?php echo $af->nombreestadosolicitud ?></td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
</div>