
<div class="row">
    <div class="col-sm-12">
        <table class="table table-bordered table-responsive" id="myTable">
            <thead>
                <tr>

                    <th>Ganancias total</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($lista3 as $g) { ?>
                    <tr>
                        <td><?php echo $g->montototal ?></td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
</div>
