
<div class="row">
    <div class="col-sm-12">
        <table class="table table-bordered table-responsive" id="myTable">
            <thead>
                <tr>

                    <th>Reclamos efectuados</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($lista6 as $r) { ?>
                    <tr>
                        <td><?php echo $r->numeroreclamo ?></td>
                        <td><?php echo $r->anioacta ?></td>
                        <td><?php echo $r->numerolibro ?></td>
                        <td><?php echo $r->numeroacta ?></td>
                        <td><?php echo $r->nombrepropietarioacta ?></td>
                        <td><?php echo $r->apellidopropietarioacta ?></td>
                        <td><?php echo $r->observaciones ?></td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
</div>
