<span>Se ha encontrado <strong><?php echo count($lista6) ?> registros</strong></span>
<div class="row">
    <div class="col-sm-12">
        <table class="table table-bordered table-responsive" id="myTable">
            <thead>
                <tr bgcolor="#AABFD7" align="center">
                    <th>N° reclamo</th>
                    <th>Usuario</th>
                    <th>Apellido</th>
                    <th>Nombre</th>
                    <th>Acta</th>
                    <th>Libro</th>
                    <th>Observaciones</th>
                    <th>Tipo de reclamo </th>
                    <th>Estado del reclamo </th>
                    <th>Fecha del reclamo </th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($lista6 as $r) { ?>
                    <tr>
                        <td><?php echo $r->id ?></td>
                        <td><?php echo $r->login ?></td>
                        <td><?php echo $r->apellidopropietarioacta ?></td>
                        <td><?php echo $r->nombrepropietarioacta ?></td>
                        <td><?php echo $r->numeroacta ?></td>
                        <td><?php echo $r->numerolibro ?></td>
                        <td><?php echo $r->observaciones ?></td>
                        <td><?php echo $r->nombretiporeclamo ?></td>
                        <td><?php echo $r->nombreestadoreclamoerroracta ?></td>
                        <td><?php echo UtilApp::formatea_fecha_bd_to_pantalla($r->fechacambioreclamoestado) ?></td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
</div>
