<span>Total de solicitudes<strong><?php echo count($lista2) ?></strong></span>
<div class="row">
    <div class="col-sm-12">
        <table class="table table-bordered table-responsive" id="myTable">
            <thead>
                <tr bgcolor="#AABFD7" align="center">
                    <th>N° de solicitud</th>
                    <th>Nombre propietario acta</th>
                    <th>Parentesco</th>
                    <th>Cupon de pago</th>
                    <th>Tipo libro</th>
                    <th>Fecha solicitud </th>
                    <th>Estado solicitud </th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($lista2 as $as) { ?>
                    <tr>
                        <td><?php echo $as->id ?></td>
                        <td><?php echo $as->nombrepropietarioacta ?></td>
                        <td><?php echo $as->nombreparentesco ?></td>
                        <td><?php echo $as->codigodepago ?></td>
                        <td><?php echo $as->nombrelibro ?></td>
                        <td><?php echo UtilApp::formatea_fecha_bd_to_pantalla($as->fechacambioestado) ?></td>
                        <td><?php echo $as->nombreestadosolicitud ?></td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
<h2 class="center"> Solicitudes</h2>
        <canvas id="canvas"></canvas>
    </div>
</div>

<!-- jQuery -->
<script src="<?php echo PUBLIC_PATH ?>gentelella/css/jquery.min.js"></script>
<!-- Bootstrap -->
<script src="<?php echo PUBLIC_PATH ?>gentelella/css/bootstrap.min.js"></script>
<!-- FastClick -->
<script src="<?php echo PUBLIC_PATH ?>gentelella/css/fastclick.js"></script>
<!-- NProgress -->
<script src="<?php echo PUBLIC_PATH ?>gentelella/css/nprogress.js"></script>
<!-- Chart.js -->
<script src="<?php echo PUBLIC_PATH ?>gentelella/css/Chart.min.js"></script>
<script src="<?php echo PUBLIC_PATH ?>gentelella/css/Chart.js"></script>
<script src="<?php echo PUBLIC_PATH ?>gentelella/css/Chart.bundle.js"></script>
<!-- Custom Theme Scripts -->
<script src="<?php echo PUBLIC_PATH ?>gentelella/css/custom.min.js"></script>
<script src="<?php echo PUBLIC_PATH ?>gentelella/css/jquery.mask.js"></script>
<script>
    var pieChartData = {
        labels: ["Generadas", "Por vencer", "Pendientes", "Firmadas"],
        datasets: [{
                label: 'Solicitudes',
                backgroundColor: [
                    "#F7464A",
                    "#46BFBD",
                    "#FDB45C",
                    "#949FB1"
                ],
                //backgroundColor: "rgba(220,220,220,0.5)",
                data: [<?php echo $sol; ?>]
            }]

    };

    window.onload = function () {
        var ctx = document.getElementById("canvas").getContext("2d");
        window.myPie = new Chart(ctx, {
            type: 'pie',
            data: pieChartData,
            options: {
                // Elements options apply to all of the options unless overridden in a dataset
                // In this case, we are setting the border of each bar to be 2px wide and green
                elements: {
                    rectangle: {
                        borderWidth: 2,
                        borderColor: 'rgb(0, 255, 0)',
                        borderSkipped: 'bottom'
                    }
                },
                responsive: true,
                legend: {
                    position: 'top',
                },
                title: {
                    display: true,
                    text: ''
                }
            }
        });

    };

</script>
