<span>Se ha encontrado <strong><?php echo count($lista2) ?> registros</strong></span>
<div class="row">
    <div class="col-sm-12">
        <table class="table table-bordered table-responsive" id="myTable">
            <thead>
                <tr>

                    <th>N° de solicitud</th>
                    <th>Nombre propietario acta</th>
                    <th>Parentesco</th>
                    <th>Cupon de pago</th>
                    <th>Tipo libro</th>
                    <th>Fecha solicitud </th>
                    <th>Estado solicitud </th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($lista2 as $as) { ?>
                    <tr>
                        <td><?php echo $as->id ?></td>
                        <td><?php echo $as->nombrepropietarioacta ?></td>
                        <td><?php echo $as->nombreparentesco ?></td>
                        <td><?php echo $as->codigodepago ?></td>
                        <td><?php echo $as->nombrelibro ?></td>
                        <td><?php echo $as->fechacambioestado ?></td>
                        <td><?php echo $as->nombreestadosolicitud ?></td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
</div>
        