<span>Se ha encontrado <strong><?php echo count($lista4) ?> registros</strong></span>
<div class="row">
    <div class="col-sm-12">
        <table class="table table-bordered table-responsive" id="myTable">
            <thead>
                <tr bgcolor="#AABFD7" align="center">
                    <th>N°</th>
                    <th>Usuario</th>
                    <th>Nombres</th>
                    <th>Apellido</th>
                    <th>dni</th>
                    <th>idTramite</th>
                    <th>Fecha alta</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($lista4 as $us) { ?>
                    <tr>
                        <td><?php echo $us->id ?></td>
                        <td><?php echo $us->login ?></td>
                        <td><?php echo $us->nombres ?></td>
                        <td><?php echo $us->apellido ?></td>
                        <td><?php echo $us->dni ?></td>
                        <td><?php echo $us->idtramite ?></td>
                        <td><?php echo UtilApp::formatea_fecha_bd_to_pantalla($us->creado_at) ?></td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
</div>
