<div class="page-header">
    <h1>Departamentos</h1>
</div>
<div id="mensajes_flash" >        
    <?php View::content() ?>
</div> 
<?php View::partial('backend/barra_superior_listas', FALSE, array('texto' => 'Crear departamento', 'opciones' => FALSE)); ?>
<?php echo Form::open('admin/departamento', 'post', 'id="formUsuario"') ?>
<div>
    <div class="conjunto">
        <?php echo Form::label('Nombre departamento', 'nombredepartamento', '') ?>
        <div >
            <?php echo Form::text('nombredepartamento') ?>
        </div>
    </div>

</div>
<?php echo Form::close() ?>
<div class="row">
    <div class="col-sm-12">
        <table class="table table-bordered table-responsive">
            <thead>
                <tr>

                    <th>Nombre</th>
                    <th>Editar</th>
                    <th>Borrar</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($listDepartamento->items as $ofi) { ?>
                    <tr>
                        <td><?php echo $ofi->nombredepartamento ?></td>
                        <td><a href="<?php echo PUBLIC_PATH . "admin/departamento/edit/" . $ofi->id ?>"><img alt="" src="<?php echo PUBLIC_PATH ?>img/figuras/editar.png"></a></td>
                        <td><a href="<?php echo PUBLIC_PATH . "admin/departamento/del/" . $ofi->id ?>"><img alt="" src="<?php echo PUBLIC_PATH ?>img/figuras/eliminar.png"></a></td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
    <?php if ($listDepartamento->prev) echo Html::linkAction("index/$listDepartamento->prev/", '<< Anterior |'); ?>
    <?php if ($listDepartamento->next) echo Html::linkAction("index/$listDepartamento->next/", 'Próximo >>'); ?>
</div>
