<div class="content">
    <?php View::content(); ?>
    <h3>Crear estado de solictud<h3>

            <?php echo Form::open(); // por defecto llama a la misma url ?>




            <label>Nombre
                <?php echo Form::text('estadosolicitud.nombreestadosolicitud') ?></label>
            <label>Descripción
                <?php echo Form::text('estadosolicitud.descripcionestadosolicitud') ?></label>
            <label>Fecha desde
                <?php echo Form::text('estadosolicitud.fechadesde', array("class" => "datemask")) ?></label>
            <label>Fecha hasta
                <?php echo Form::text('estadosolicitud.fechahasta', array("class" => "datemask")) ?></label>
            <?php echo Form::submit('Agregar') ?>

            <?php echo Form::close() ?>
            </div>