<div class="content">
    <?php View::content(); ?>
    <h3>Editar estados de solicitud<h3>
    <div class="row">
        <?php echo Form::open(); // por defecto llama a la misma url ?>

        <div class="form-group">

            <label class="control-label col-sm-2">Nombre
                <?php echo Form::text('estadosolicitud.nombreestadosolicitud', array("class" => " form-control col-sm-10 ")) ?></label>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-2">Descripcion
                <?php echo Form::text('estadosolicitud.descripcionestadosolicitud', array("class" => " form-control col-sm-10 ")) ?></label>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-2">Fecha desde
                <?php echo Form::text('estadosolicitud.fechadesde', array("class" => " form-control col-sm-10 datemask")) ?></label>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-2">Fecha hasta
                <?php echo Form::text('estadosolicitud.fechahasta', array("class" => "datemask form-control col-sm-10 ")) ?></label>
        </div>
        <?php echo Form::hidden('estadosolicitud.id') ?>
        <?php echo Form::submit('Actualizar') ?>

        <?php echo Form::close() ?>
    </div>
</div>