<div class="page-header">
    <h1>Crear Usuario</h1>
</div>
<div class="row">
    <div class="col-sm-3">
        <?php View::partial('backend/menus/usuarios') ?>
    </div>
    <div class="col-sm-6">
    <div class="widget-box widget-color-dark light-border ui-sortable-handle">
        <div class="widget-header">
            <h5 class="widget-title smaller">Datos Nuevo</h5>
        </div>

        <div class="widget-body">
            <div class="widget-main">
                <div class="alert alert-info"> 
			        <div id="res-form-ajax"><?php View::content() ?></div>
			        <?php echo Ajax::form('res-form-ajax', NULL, 'form-horizontal') ?>
			        <?php //echo Form::open(NULL, 'post', 'class="form-horizontal"') ?>
			        <?php echo Form::hidden('usuario.id') ?>
			        <div class="control-group">
			            <label class="control-label" for="usuario_login">Nombre de Usuario (Login)* : </label>
			            <div class="controls">
			                <?php echo Form::text('usuario.login') ?>
			            </div>
			        </div>
			        <div class="control-group">
			            <label class="control-label" for="usuario_clave">Contrase&ntilde;a* : </label>
			            <div class="controls">
			                <?php echo Form::pass('usuario.clave') ?>
			            </div>
			        </div>
			        <div class="control-group">
			            <label class="control-label" for="usuario_clave2">Volver a escribir Contrase&ntilde;a* : </label>
			            <div class="controls">
			                <?php echo Form::pass('usuario.clave2') ?>
			            </div>
			        </div>
			        <div class="control-group">
			            <label class="control-label" for="usuario_nombres">Nombre Completo* : </label>
			            <div class="controls">
			                <?php echo Form::text('usuario.nombres') ?>
			            </div>
			        </div>
			        <div class="control-group">
			            <label class="control-label" for="usuario_email">Correo Electronico* : </label>
			            <div class="controls">
			                <?php echo Form::text('usuario.email') ?>
			            </div>
			        </div>
			        
			        <div class="control-group">
			            <label class="control-label" for="usuario_email">Oficina*  ( Código / Nombre ):  </label>
			            <div class="controls">
			                <?php View::partial("autocompletes/oficina", null, array("field" => "usuario.base_oficina_id", "attr" => array("class" => "col-xs-12 col-sm-12"), 1)); ?>
			            </div>
			        </div>
			      
			        <div class="control-group">
			            <label class="control-label" for="usuario_roles_id">Roles del Usuario* : </label><br/><br/>
			            <div class="controls">
			                <ul>
			                    <?php foreach ($roles as $e): ?>
			                        <li><?php echo Form::check("rolesUser.$e->id", $e->id), ' ', h($e->rol) ?></li>
			                    <?php endforeach; ?>
			                    </ul>
			                </div>
		            </div>
		            
			            
    				</div>
                </div>
            </div>
        </div>
	</div>							        
 </div>   
 <div class="row">
 	<div class="form-actions">
        <?php echo Form::submit('Guardar Datos', 'class="btn btn-primary"') ?>
        <?php echo Html::linkAction('', 'Cancelar', 'class="btn"') ?>
    </div>
    <?php echo Form::close() ?>
   </div> 
 </div>   
</div>