<div class="page-header">
    <h1>Crear Usuario</h1>
</div>
<div class="row">
    <div class="col-sm-3">
        <?php View::partial('backend/menus/usuarios') ?>
    </div>
    <div class="col-sm-6">
        <div class="widget-box widget-color-dark light-border ui-sortable-handle">
            <div class="widget-header">
                <h5 class="widget-title smaller">Datos Nuevo</h5>
            </div>

            <div class="widget-body">
                <div class="widget-main">
                    <div class="alert alert-info"> 
                        <div id="res-form-ajax"><?php View::content() ?></div>
                        <?php echo Ajax::form('res-form-ajax', NULL, 'form-horizontal') ?>
                        <?php //echo Form::open(NULL, 'post', 'class="form-horizontal"') ?>
                        <div class="control-group">
                            <label class="control-label" for="usuario_login">Nombre de Usuario (Login)* : </label>
                            <div class="controls">
                                <?php echo Form::text('usuario.login') ?>
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label" for="usuario_clave">Contrase&ntilde;a* : </label>
                            <div class="controls">
                                <?php echo Form::pass('usuario.clave') ?>
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label" for="usuario_clave2">Volver a escribir Contrase&ntilde;a* : </label>
                            <div class="controls">
                                <?php echo Form::pass('usuario.clave2') ?>
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label" for="usuario_dni">DNI* : </label>
                            <div class="controls">
                                <?php echo Form::text('usuario.dni') ?>
                            </div>
                        </div>                        
                        <div class="control-group">
                            <label class="control-label" for="usuario_nombres">Nombre: </label>
                            <div class="controls">
                                <?php echo Form::text('usuario.nombres',array("disabled"=>"disabled")) ?>
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label" for="usuario_apellido">Apellido: </label>
                            <div class="controls">
                                <?php echo Form::text('usuario.apellido',array("disabled"=>"disabled")) ?>
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label" for="usuario_email">Correo Electronico* : </label>
                            <div class="controls">
                                <?php echo Form::text('usuario.email') ?>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label" for="usuario_roles_id">Roles del Usuario* : </label><br/><br/>
                            <div class="controls">
                                <ul>
                                    <?php foreach ($roles as $e): ?>
                                        <li><?php echo Form::check("rolesUser.$e->id", $e->id), ' ', h($e->rol) ?></li>
                                    <?php endforeach; ?>
                                </ul>
                            </div>
                        </div>


                    </div>
                </div>
            </div>
        </div>
    </div>							        
</div>   
<div class="row">
    <div class="form-actions">
        <?php echo Form::submit('Guardar Datos', 'class="btn btn-primary"') ?>
        <?php echo Html::linkAction('', 'Cancelar', 'class="btn"') ?>
    </div>
    <?php echo Form::close() ?>
</div> 
<script>
$("#usuario_dni").change(function () {
        $("#usuario_nombres").val("");
        $("#usuario_apellido").val("");
        $("#usuario_nombres").removeAttr("readonly")
        $("#usuario_nombres").removeAttr("disabled")
        $("#usuario_apellido").removeAttr("readonly")
        $("#usuario_apellido").removeAttr("disabled")
        $.ajax({
            data: {
                'dni': $("#usuario_dni").val()
            },
            url: "<?php echo PUBLIC_PATH ?>tramitedni/buscar_ciudadano_por_documento",
            type: 'post',
            dataType: "json",
            success: function (response) {
                $("#usuario_nombres").val(response.nombres);
                $("#usuario_apellido").val(response.apellido);
                $("#usuario_nombres").attr("readonly", "readonly")
                $("#usuario_apellido").attr("readonly", "readonly")
            }
        });

    });
</script>