<div class="page-header">
    <h1>Usuarios del Sistema</h1>
</div>
<div id="mensajes_flash" >        
    <?php View::content() ?>
</div> 
<?php View::partial('backend/barra_superior_listas', FALSE, array('texto' => 'Crear Usuario', 'opciones' => FALSE)); ?>
<?php echo Form::open('admin/usuarios', 'post', 'id="formUsuario"') ?>
<div>
    <div class="conjunto">
        <?php echo Form::label('Nombre Usuario', 'nombre_usuario', '') ?>
        <div >
            <?php echo Form::text('nombre_usuario') ?>


        </div>
    </div>
    <div class="conjunto">
        <?php echo Form::label('Oficina', 'oficina_id', '') ?>
        <div >
            <?php echo Form::dbSelect('oficina_id', 'descripcion', array("base_oficina", "buscar_todos"), "Buscar por ...", 1) ?>
            <?php echo Form::submit('buscar') ?>
        </div>
    </div>

</div>
<?php echo Form::close() ?>
<div class="row">
    <div class="col-sm-12">
        <table class="table table-bordered table-responsive">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Login</th>
                    <th>Nombre</th>
                    <th>Correo</th>
                    <!--<th>Estado</th>-->
                    <th>Editar</th>
                    <th>Blanquear Clave</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($usuarios->items as $menu) { ?>
                    <tr>
                        <td><?php echo $menu->id ?></td>
                        <td><?php echo $menu->login ?></td>
                        <td><?php echo $menu->nombres ?></td>
                        <td><?php echo $menu->email ?></td>
                        <!--<td><a href="/admin/usuarios/editar/<?php echo $menu->id ?>"><img alt="" src="/img/figuras/editar.png"> </a></td>-->
                        <td><a href="<?php echo PUBLIC_PATH . "admin/usuarios/editar/" . $menu->id ?>">Editar</a></td>
                        <td><a href="<?php echo PUBLIC_PATH . "admin/usuarios/blanquear_clave/" . $menu->id ?>">Blanquear</a></td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
</div>

<?php //View::partial('paginators/bootstrap', false, array('page' => $usuarios, 'url' => Router::get('controller_path') . '/index')); ?>
<?php View::partial('paginators/bootstrap_ajax', false, array('page' => $usuarios, 'url' => Router::get('controller_path') . '/index')); ?> 