<div class="page-header">
    <h1>Usuarios del Sistema</h1>
</div>
<div id="mensajes_flash" >        
    <?php View::content() ?>
</div> 
<?php View::partial('backend/barra_superior_listas', FALSE, array('texto' => 'Crear Usuario', 'opciones' => FALSE)); ?>
<?php echo Form::open('admin/usuarios', 'post', 'id="formUsuario"') ?>
<div>
    <div class="conjunto">
        <?php echo Form::label('Nombre Usuario', 'nombre_usuario', '') ?>
        <div >
            <?php echo Form::text('nombre_usuario') ?>


        </div>
    </div>

</div>
<?php echo Form::close() ?>
<div class="row">
    <div class="col-sm-12">
        <table class="table table-bordered table-responsive">
            <thead>
                <tr>
                    <th>Login</th>
                    <th>Nombre</th>
                    <th>idTramite</th>
                    <th>DNI</th>
                    <th>Correo</th>
                    <!--<th>Estado</th>-->
                    <th>Editar</th>
                    <th>Blanquear Clave</th>
                    <th>Estado</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($usuarios->items as $dni) { ?>
                    <tr>
                        <td><?php echo $dni->login ?></td>
                        <td><?php echo $dni->nombres ?></td>
                        <td><?php echo $dni->idtramite ?></td>
                        <td><?php echo $dni->dni ?></td>
                        <td><?php echo $dni->email ?></td>
                        <td><a href="<?php echo PUBLIC_PATH . "admin/usuarios/editar/" . $dni->id ?>">Editar</a></td>
                        <td><a href="<?php echo PUBLIC_PATH . "admin/usuarios/blanquear_clave/" . $dni->id ?>">Blanquear</a></td>
                        <?php if ($dni->activo == 0) { ?>
                            <td><a href="<?php echo PUBLIC_PATH . "admin/usuarios/activar/" . $dni->id ?>"><img alt="" src="<?php echo PUBLIC_PATH ?>img/figuras/circulo_rojo.png"></a></td>
                        <?php } else { ?>
                            <td><a href="<?php echo PUBLIC_PATH . "admin/usuarios/desactivar/" . $dni->id ?>"><img alt="" src="<?php echo PUBLIC_PATH ?>img/figuras/circulo_verde.png"></a></td>
                        <?php } ?>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
</div>

<?php //View::partial('paginators/bootstrap', false, array('page' => $usuarios, 'url' => Router::get('controller_path') . '/index')); ?>
<?php View::partial('paginators/bootstrap_ajax', false, array('page' => $usuarios, 'url' => Router::get('controller_path') . '/index')); ?> 