<div class="content">
    <?php View::content(); ?>
    <h3>Codigos provinciales</h3>
    <ul>
    <?php foreach ($listCodigoprovincial->items as $item) : ?>
    <li>
        <?php echo Html::linkAction("edit/$item->id/", 'Editar') ?>
        <?php echo Html::linkAction("del/$item->id/", 'Borrar') ?>
        <strong><?php echo $item->importecodigo ?> - <?php echo $item->numerocodigoprovincial ?> -<?php echo $item->fechadesde ?> - <?php echo $item->fechahasta ?></strong>
        
    </li>
    <?php endforeach; ?>
    </ul>
 
     <!-- ejemplo manual de paginador, hay partial listos en formato digg, clasic,.... -->
    <?php if($listCodigoprovincial->prev) echo Html::linkAction("index/$listCodigoprovincial->prev/", '<< Anterior |'); ?>
    <?php if($listCodigoprovincial->next) echo Html::linkAction("index/$listCodigoprovincial->next/", 'Próximo >>'); ?>
</div>