<style>
    #acciones .fuente {
        font-size: 14px;
    }
    #acciones .titulo {
        color: #f8f8f8;
        text-align: center;
    }
    #acciones {
        background-color: #6fb3e0;
    }
</style>

<div class="row">
    <div class="span12">
        <?php echo View::content() ?>
    </div>
</div>

<div id = "acciones" class="row action-buttons " >
    
    <div class="col-xs-12 col-sm-12">
        
        <a class="btn btn-white btn-primary btn-bold col-xs-12 col-sm-1" href="<?php echo PUBLIC_PATH ?>oficina/crear">
            <i class="ace-icon fa fa-file-text-o bigger-300" title="Crear Oficina"> 
                <p class="fuente">Crear</p>
            </i>
        </a>
        
        <h1 class="widget-title col-xs-8 col-sm-8  titulo">Oficina</h1>
        
        <a class="btn btn-white btn-primary btn-bold col-xs-1 col-sm-1 pull-right" href="#">
            <i class="ace-icon fa fa-eraser bigger-300" title="Limpiar" onclick="limpiar_campos();">
                <p class="fuente">Limpiar</p>
            </i>
        </a>
        
        <a class="btn btn-white btn-primary btn-bold col-xs-1 col-sm-1 pull-right" href="#">
            <i class="ace-icon fa fa-arrow-left bigger-300" title="Volver" onclick="volver();">
                <p class="fuente">Volver</p>
            </i>
        </a>
    
    </div>

</div>

<div class="row">
    
    <div class="col-sm-12">
        <div class="widget-box">
            <div class="widget-header tramite_color">
                <h5 class="widget-title"><i class="fa fa-file"></i> Filtros</h5>
                <span class="widget-toolbar">
                    <a href="#" data-action="collapse">
                        <i class="ace-icon fa fa-chevron-up"></i>
                    </a>
                </span>
            </div>

            <div class="widget-body">

                <div class="widget-main">
                    <?php echo Form::open("", "post", array("id" => "formCriterioOficina", "class" => "form-horizontal")); ?>

                    <div class="row pan_filtro libro" title="Filtro por datos de la oficina" id="datos_libro">
                        <div class="col-xs-12 col-sm-12">
                            <div class="form-group">

                                <?php echo Form::label('Numero', 'criterio_numero', 'class="col-sm-1 no-padding-right"') ?>
                                <div class="col-sm-1">
                                    <?php echo Form::text('criterio.numero', array("class" => "col-xs-12 col-sm-12 limpiable")) ?>
                                </div>
    
                                <?php echo Form::label('Nombre', 'criterio_nombre', 'class="col-sm-1 no-padding-right"') ?>
                                <div class="col-sm-2">
                                    <?php echo Form::text('criterio.nombre', array("class" => "col-xs-12 col-sm-12 limpiable")) ?>
                                </div>
        
                                <?php echo Form::label('Departamento', 'criterio_departamento', 'class="col-sm-1 no-padding-right"') ?>
                                <div class="col-sm-2">
                                    <?php echo Form::dbSelect('criterio.departamento', 'nombre', array("base_ubicacion", "buscar_departamento_por_provincia_id", UBICACION_MENDOZA), "Todos", array("class" => "col-xs-12 col-sm-12 limpiable")) ?>
                                </div>
                                   
                            </div>

                            <div class="form-group">

                                <div class="conjunto">
                                    <?php echo Form::label('Oficinas que enlazan', 'criterio_enlaza', 'class="col-sm-1 no-padding-right"') ?>
                                    <div class="col-sm-2">
                                        <?php echo Form::check("criterio.enlaza", 1, ' ', false) ?>
                                    </div>
                                </div>
                                
                                <div class="conjunto">
                                    <?php echo Form::label('Oficina a enviar notificacion', 'criterio_enviar_notificacion', 'class="col-sm-1 no-padding-right"') ?>
                                    <div class="col-sm-2">
                                        <?php echo Form::check("criterio.enviar_notificacion", 1, ' ', false) ?>
                                    </div>
                                </div>
                                
                                <div class="conjunto">
                                    <?php echo Form::label('Oficina cabecera', 'criterio_cabecera', 'class="col-sm-1 no-padding-right"') ?>
                                    <div class="col-sm-2">
                                        <?php echo Form::check("criterio.cabecera", 1, ' ', false) ?>
                                    </div>
                                </div>
                                
                                <?php echo Form::submit('Consultar', 'class="btn btn-pink pull-right"') ?>                             
     
                            </div>       
                        </div>
                    </div>
                </div>
            </div>
            <?php echo Form::close(); ?>
         </div>
    </div>
</div>

<div class="clearfix">
    <div class="pull-left opciones">

        <a class="btn btn-white btn-yellow btn-bold btn-sm disabled ver" href="#">
            <i class="ace-icon fa fa-search bigger-160"></i>
            Ver Información
        </a>

        <a class="btn btn-white btn-success btn-bold btn-sm disabled editar" href="#">
            <i class="ace-icon fa fa-pencil-square-o bigger-160"></i>
            Editar
        </a>

        <a class="btn btn-white btn-info btn-bold btn-sm disabled tramite" href="#">
            <i class="ace-icon fa fa-users bigger-160"></i>
            Retirar Toner
        </a>

    </div>
</div>

<?php echo Tag::js("table/jquery.dataTables.min"); ?>

<?php if (isset($oficinas) && count($oficinas) > 0) { ?>
    <div class="dataTables_wrapper form-inline no-footer">
        
        <table class="table  table-bordered table-hover dataTable no-footer table-striped" id="tabla_oficinas" role="grid" aria-describedby="dynamic-table_info">
            
            <thead>
                <tr role="row">
                    <th class="hidden-480 sorting" tabindex="0" aria-controls="dynamic-table" rowspan="1" colspan="1" aria-label="Numero: activate to sort column ascending">Numero</th>
                    <th class="hidden-480 sorting" tabindex="0" aria-controls="dynamic-table" rowspan="1" colspan="1" aria-label="Nombre: activate to sort column ascending">Nombre</th>
                    <th class="hidden-480 sorting" tabindex="0" aria-controls="dynamic-table" rowspan="1" colspan="1" aria-label="CIDR: activate to sort column ascending">CIDR</th>
                    <th class="hidden-480 sorting" tabindex="0" aria-controls="dynamic-table" rowspan="1" colspan="1" aria-label="Referencia CDR: activate to sort column ascending">Referencia CDR</th>
                </tr>
            </thead>
            
            <tbody>
                <?php
                if (count($oficinas) > 0):
                    foreach ($oficinas->items as $ofi):
                        ?>
                            <tr class="odd" role="row" data-id="<?php echo $ofi->id ?>">
                                <td class = ""><?php echo $ofi->numero ?></td>
                                <td class = ""><?php echo $ofi->nombre ?></td>
                                <td class = ""><?php echo $ofi->cidr ?></td>
                                <td class = ""><?php echo $ofi->referencia_cdr ?></td>
                            </tr>
                        <?php
                    endforeach;
                endif;
                ?>
            </tbody>
        </table>
    </div>
    <?php
    View::partial('paginators/bootstrap_ajax', false, array('form' => "formCriterioOficina", 'page' => $oficinas, 'url' => Router::get('controller_path') . '/index'));
}
?>

<script type="text/javascript">
    $(document).on("click", ".accvisualizar", function() {
        $(this).parent().parent().parent().find("form.formVisualizar").submit();
    });
    $(document).on("click", ".accpedido", function() {
        $("#formPedido").submit();
    });

    columnas = [
        {"sWidth": "25%"}, // 1st column width
        {"sWidth": "3%"}, // 2nd column width
        {"sWidth": "3%"}, // 2nd column width
        {"sWidth": "3%"}, // 2nd column widthh
        {"sWidth": "5%"}, // 2nd column widthh
        {"sWidth": "15%"}, // 2nd column width
        {"sWidth": "6%"}, // 2nd column width
        {"sWidth": "15%"}, // 2nd column width
        {"sWidth": "6%"}, // 2nd column width
        {"sWidth": "3%"}, // 2nd column width
        {"sWidth": "16%"} // 2nd column width
    ];

    $('.datatable').dataTable({
        "bPaginate": false,
        "bInfo": false,
        "oLanguage": {
            "sSearch": "Busqueda Rápida:",
            "sZeroRecords": "No se ha encontrado ningun resultado"
        },
        "bAutoWidth": false, // Disable the auto width calculation
        "aoColumns": columnas
    });

    $('#tabla_oficinas tr').click(function() {
        $(this).attr('data-id');
        $('#tabla_oficinas tr').removeClass("info");
        $('.opciones a.btn').removeClass("disabled");
        $(this).addClass("info");
        $('.ver').attr('href', '<?php echo PUBLIC_PATH ?>admin/oficina/ver/' + $(this).attr('data-id'));
        $('.editar').attr('href', '<?php echo PUBLIC_PATH ?>admin/oficina/editar/' + $(this).attr('data-id'));
    });

    function limpiar_campos() {
        $(".limpiable").val("");
//        $(".limpiable_nac_desde").val(<?php // echo UtilApp::fecha_actual('Y') ?>);
//        $(".limpiable_nac_hasta").val(<?php // echo UtilApp::fecha_actual('d/m/Y') ?>);
    }
</script>