<div class="content">
    <?php View::content(); ?>
    <h3>Crear tipos de reportes<h3>

            <?php echo Form::open(); // por defecto llama a la misma url ?>
            <label>Nombre
                <?php echo Form::text('tiporeporte.nombretiporeporte') ?></label>
            <label>Descripcion
                <?php echo Form::text('tiporeporte.descripciontiporeporte') ?></label>
            <label>Fecha desde
                <?php echo Form::text('tiporeporte.fechadesde', array("class" => "datemask")) ?></label>
            <label>Fecha hasta
                <?php echo Form::text('tiporeporte.fechahasta', array("class" => "datemask")) ?></label>
            <?php echo Form::submit('Agregar') ?>
            <?php echo Form::close() ?>
            </div>