<div class="content">
    <?php View::content(); ?>
    <h3>Editar tipos de reportes<h3>

            <?php echo Form::open(); // por defecto llama a la misma url ?>
            <label>Nombre
                <?php echo Form::text('tiporeporte.nombretiporeporte') ?></label>
            <label>Descripcion
                <?php echo Form::text('tiporeporte.descripciontiporeporte') ?></label>
            <label>Fecha desde
                <?php echo Form::text('tiporeporte.fechadesde') ?></label>
            <label>Fecha hasta
                <?php echo Form::text('tiporeporte.fechahasta') ?></label>
            <?php echo Form::hidden('tiporeporte.id') ?>
            <?php echo Form::submit('Actualizar') ?>
            <?php echo Form::close() ?>
            </div>