<div class="content">
    <?php View::content(); ?>
    <h3>Editar Rol<h3>

            <?php echo Form::open(); // por defecto llama a la misma url ?>
            <label>Descripcion
                <?php echo Form::text('rol.descripcionrol') ?></label>
            <label>Nombre
                <?php echo Form::text('rol.nombrerol') ?></label>
            <label>Fecha baja
                <?php echo Form::text('rol.fechabajarol') ?></label>
            <?php echo Form::hidden('rol.id') ?>
            <?php echo Form::submit('Actualizar') ?>

            <?php echo Form::close() ?>
            </div>