<div class="content">
    <?php View::content(); ?>
    <h3>Rol</h3>
    <ul>
    <?php foreach ($listRol->items as $item) : ?>
    <li>
        <?php echo Html::linkAction("edit/$item->id/", 'Editar') ?>
        <?php echo Html::linkAction("del/$item->id/", 'Borrar') ?>
        <strong><?php echo $item->descripcionrol ?> - <?php echo $item->nombrerol ?> - <?php echo $item->fechabajarol ?></strong>
    </li>
    <?php endforeach; ?>
    </ul>
 
     <!-- ejemplo manual de paginador, hay partial listos en formato digg, clasic,.... -->
    <?php if($listRol->prev) echo Html::linkAction("index/$listRol->prev/", '<< Anterior |'); ?>
    <?php if($listRol->next) echo Html::linkAction("index/$listRol->next/", 'Próximo >>'); ?>
</div>