<div class="content">
    <?php View::content(); ?>
    <h3>Parentesco</h3>
    <ul>
    <?php foreach ($listParentesco->items as $item) : ?>
    <li>
        <?php echo Html::linkAction("edit/$item->id/", 'Editar') ?>
        <?php echo Html::linkAction("del/$item->id/", 'Borrar') ?>
        <strong><?php echo $item->nombreparentesco?> - <?php echo $item->fechaaltaparentesco?> - <?php echo $item->fechabajaparentesco?></strong>
    </li>
    <?php endforeach; ?>
    </ul>
 
     <!-- ejemplo manual de paginador, hay partial listos en formato digg, clasic,.... -->
    <?php if($listParentesco->prev) echo Html::linkAction("index/$listParentesco->prev/", '<< Anterior |'); ?>
    <?php if($listParentesco->next) echo Html::linkAction("index/$listParentesco->next/", 'Próximo >>'); ?>
</div>

