<div class="content">
    <?php View::content(); ?>
    <h3>Editar tipos de libros<h3>
            <div class="row">
                <?php echo Form::open(); // por defecto llama a la misma url ?>
                <label>Nombre
                    <?php echo Form::text('tipolibro.nombrelibro') ?></label>
                <label>Fecha desde
                    <?php echo Form::text('tipolibro.fechadesde', array("class" => "datemask")) ?></label>
                <label>Fecha hasta
                    <?php echo Form::text('tipolibro.fechahasta', array("class" => "datemask")) ?></label>
                <?php echo Form::hidden('tipolibro.id') ?>
                <?php echo Form::submit('Actualizar') ?>
                <?php echo Form::close() ?>
            </div>