<div class="page-header">
    <h1>Localidades</h1>
</div>
<div id="mensajes_flash" >        
    <?php View::content() ?>
</div> 
<?php View::partial('backend/barra_superior_listas', FALSE, array('texto' => 'Crear localidad', 'opciones' => FALSE)); ?>
<?php echo Form::open('admin/localidad', 'post', 'id="formUsuario"') ?>
<div>
    <div class="conjunto">
        <?php echo Form::label('Nombre localidad', 'nombrelocalidad', '') ?>
        <div >
            <?php echo Form::text('nombrelocalidad') ?>
        </div>
    </div>

</div>
<?php echo Form::close() ?>
<div class="row">
    <div class="col-sm-12">
        <table class="table table-bordered table-responsive">
            <thead>
                <tr>

                    <th>Nombre</th>
                    <th>Editar</th>
                    <th>Borrar</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($listLocalidad->items as $l) { ?>
                    <tr>
                        <td><?php echo $l->nombrelocalidad?></td>
                        <td><a href="<?php echo PUBLIC_PATH . "admin/localidad/edit/" . $l->id ?>"><img alt="" src="<?php echo PUBLIC_PATH ?>/img/figuras/editar.png"></a></td>
                        <td><a href="<?php echo PUBLIC_PATH . "admin/localidad/del/" . $l->id ?>"><img alt="" src="<?php echo PUBLIC_PATH ?>/img/figuras/eliminar.png"></a></td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
    <?php if ($listLocalidad->prev) echo Html::linkAction("index/$listLocalidad->prev/", '<< Anterior |'); ?>
    <?php if ($listLocalidad->next) echo Html::linkAction("index/$listLocalidad->next/", 'Próximo >>'); ?>
</div>
