<?php
if (!isset($url)) {
    extract(Router::get(), 0);
    $url = "$controller/$action";
    if ($module) {
        $url = "$module/$url";
    }
}

if (!isset($show)) {
    $show = 10;
}

$half = floor($show / 2);

//Calculando el inicio de paginador centrado
if ($page->current <= $half) {
    $start = 1;
} elseif (($page->total - $page->current) < $half) {
    $start = $page->total - $show + 1;
    if ($start < 1)
        $start = 1;
} else {
    $start = $page->current - $half;
}
?>
<div class="dataTables_paginate paging_simple_numbers">
    <ul class="pagination">
        <?php
        if ($page->prev) {
            echo '<li class="prev">', Form::button('Anterior', "onclick='buscar_datos($page->prev)'", 'title="Ir a la pág. anterior"'), '</li>'; // Se coloca el link sin numero de pagina para la pagina 1
        } else {
            echo '<li class="prev  disabled"><a title="Ir a la pág. anterior" href="#">Anterior</a></li>';
        }
        ?>
        <?php
        if ($start == 1) { //se coloca el link sin numero de pagina para la pagina 1
            $start = 2;
            $show -= 1;
            echo $page->current == 1 ? "<li class=\"active\"><a href='#'>1</a><li>" : '<li>' . Form::button('1', "onclick='buscar_datos(1)'") . '</li>';
        } elseif ($start > 1) {
            echo '<li>', Form::button('1', "onclick='buscar_datos(1)'"), '</li>';
        }
        if ($start > 2):
            ?>
            <li><a href="#">...</a></li>
        <?php endif; ?>

        <?php for ($i = $start; $i <= $page->total && $i < ($start + $show); $i++): ?>
            <?php echo $i == $page->current ? "<li class=\"active\"><a href='#'>$i</a><li>" : '<li>' . Form::button($i, "onclick='buscar_datos($i)'") . '</li>'; ?>
        <?php endfor; ?>

        <?php if ($page->total > $i): ?>
            <li><a href="#">...</a></li>
            <?php echo '<li>', Form::button($page->total, "onclick='buscar_datos($page->total)'"), '</li>'; ?>
        <?php elseif ($i == $page->total): ?>
            <?php echo '<li>', Form::button($i, "onclick='buscar_datos($i)'"), '</li>'; ?>
        <?php endif; ?>

        <?php
        if ($page->next) {
            echo '<li>', Form::button('Siguiente', "onclick='buscar_datos($page->next)'", 'title="Ir a la pág. siguiente" class="nextprev"'), '</li>';
        } else {
            echo '<li class="disabled"><a title="Ir a la pág. siguiente" href="#">Siguiente</a></li>';
        }
        ?>
    </ul>
</div>
<script>
    
        function buscar_datos(pagina){
            url = "<?php echo PUBLIC_PATH . $url ?>/"+pagina;
            $(<?php echo "'#$form'" ?>).attr("action", url);
            $(<?php echo "'#$form'" ?>).submit();
        }
</script>
