<div class="content">
<?php View::content(); ?>
<h3>Crear Tipo de reclamo<h3>
 
<?php echo Form::open(); // por defecto llama a la misma url ?>
 
        
 
        
        <label>Nombre
        <?php echo Form::text('tiporeclamo.nombretiporeclamo') ?></label>
        <label>Descripción
        <?php echo Form::text('tiporeclamo.descripciontiporeclamo') ?></label>
        <label>Fecha baja
        <?php echo Form::text('tiporeclamo.fechabajatiporeclamo') ?></label>
        
        
        
 
        <?php echo Form::submit('Agregar') ?>
 
<?php echo Form::close() ?>
</div>