<div class="content">
    <?php View::content(); ?>
    <h3>Tipo Reclamo</h3>
    <ul>
    <?php foreach ($listTiporeclamo->items as $item) : ?>
    <li>
        <?php echo Html::linkAction("edit/$item->id/", 'Editar') ?>
        <?php echo Html::linkAction("del/$item->id/", 'Borrar') ?>
        <strong><?php echo $item->nombretiporeclamo ?> - <?php echo $item->descripciontiporeclamo ?> - <?php echo $item->fechabajatiporeclamo ?></strong>
    </li>
    <?php endforeach; ?>
    </ul>
 
     <!-- ejemplo manual de paginador, hay partial listos en formato digg, clasic,.... -->
    <?php if($listTiporeclamo->prev) echo Html::linkAction("index/$listTiporeclamo->prev/", '<< Anterior |'); ?>
    <?php if($listTiporeclamo->next) echo Html::linkAction("index/$listTiporeclamo->next/", 'Próximo >>'); ?>
</div>