<div class="content">
    <?php View::content(); ?>
    <h3>Crear Usuario<h3>

            <?php echo Form::open(); // por defecto llama a la misma url ?>
            <label>Apellido 
                <?php echo Form::text('usuario.apellidousuario') ?></label>
            <label>Nombre 
                <?php echo Form::text('usuario.nombreusuario') ?></label>
            <label>e-mail 
                <?php echo Form::text('usuario.correoelectronico') ?></label>
            <label>DNI
                <?php echo Form::text('usuario.dni') ?></label>
            <label>Celular
                <?php echo Form::text('usuario.celular') ?></label>
            <label>Telefono fijo
                <?php echo Form::text('usuario.celular') ?></label>
            <label>Sexo
                <?php echo Form::text('usuario.celular') ?></label>
            <label>Usuario
                <?php echo Form::text('usuario.celular') ?></label>
            <label>Clave 
                <?php echo Form::text('usuario.pass') ?></label>

            <?php echo Form::submit('Agregar') ?>

            <?php echo Form::close() ?>
            </div>